import type { BlenderNode } from "./types";

export const COMPOSITOR_NODES: BlenderNode[] = [

  // ── INPUT ──────────────────────────────────────────────────────────────────

  {
    id: "comp-render-layers",
    name: "Render Layers",
    category: "compositor-nodes",
    subcategory: "Input",
    icon: "🎬",
    color: "blue",
    description: "Brings a rendered image and its render passes into the compositor.",
    whyItExists: "The compositor works on rendered output, not live 3D data. This node is the bridge.",
    whenToUse: "Always — it's the starting point of almost every compositor setup.",
    inputs: [],
    outputs: [
      { name: "Image", type: "Color", description: "Combined render output (beauty pass)" },
      { name: "Alpha", type: "Float", description: "Alpha channel of the render" },
      { name: "Depth", type: "Float", description: "Z-depth pass (distance from camera)" },
      { name: "Normal", type: "Vector", description: "Surface normals pass" },
      { name: "Diffuse Direct", type: "Color", description: "Direct diffuse lighting pass" },
      { name: "Diffuse Indirect", type: "Color", description: "Indirect diffuse (bounced light)" },
      { name: "Glossy Direct", type: "Color", description: "Direct specular/glossy pass" },
      { name: "Shadow", type: "Color", description: "Shadow pass for compositing control" },
    ],
    beginnerExplanation: "This is like pressing 'play' to load your render into the compositor — everything starts here.",
    advancedExplanation: "Each output corresponds to an enabled render pass in Properties → View Layer → Passes. Enable passes before rendering to get access to them here. Cryptomatte, AO, and other passes also appear as extra outputs when enabled.",
    commonUseCases: [
      "Starting point for color grading your render",
      "Using depth pass to add atmospheric fog",
      "Separating gloss/diffuse for targeted adjustments",
    ],
    typicalConnections: ["Render Layers", "→", "Glare", "→", "Composite"],
    exampleWorkflow: "Enable View Layer passes → Render → Open Compositor → Render Layers node is already there → connect Image to Composite node",
    commonMistakes: [
      "Forgetting to enable render passes before rendering (they'll appear but be black)",
      "Using the node with an outdated/empty render — always re-render after scene changes",
    ],
    performanceTips: ["Only enable the render passes you actually need — unused passes increase memory and render time"],
    relatedNodes: ["comp-composite", "comp-viewer", "comp-image"],
    frequentlyUsedWith: ["comp-composite", "comp-glare", "comp-color-balance"],
    screenshotPlaceholder: "Render Layers node showing Image, Alpha, Depth outputs connected in compositor",
    quiz: [{ question: "What must you do in Properties before render passes appear here?", answer: "Enable the passes in Properties → View Layer → Passes before rendering." }],
    practiceExercise: "Enable the Depth pass, render your scene, then use the depth output to add a fog effect with a Mix node.",
    blenderVersion: "4.4",
    lastVerified: "2025-03",
    tags: ["render", "input", "passes", "depth", "compositor", "beauty"],
  },

  {
    id: "comp-image",
    name: "Image",
    category: "compositor-nodes",
    subcategory: "Input",
    icon: "🖼️",
    color: "blue",
    description: "Loads an external image or image sequence for use in the compositor.",
    whyItExists: "Lets you composite external files (textures, photos, pre-rendered elements) without needing a render.",
    whenToUse: "When layering an external photo/plate with your render, or using a pre-rendered EXR sequence.",
    inputs: [],
    outputs: [
      { name: "Image", type: "Color", description: "The loaded image" },
      { name: "Alpha", type: "Float", description: "Alpha channel if the image has one" },
    ],
    beginnerExplanation: "It's like File → Open Image, but inside the compositor so you can blend it with your render.",
    advancedExplanation: "Supports all Blender-supported formats including multi-layer EXR. For sequences, set the frame range and use Image → Sequence mode. Supports UDIM tiles when set to UDIM mode.",
    commonUseCases: [
      "Loading a background plate to composite your 3D render onto",
      "Bringing in a pre-rendered shadow catcher layer",
      "Loading a lens flare texture to overlay",
    ],
    typicalConnections: ["Image", "→", "Alpha Over", "→", "Composite"],
    exampleWorkflow: "Add Image node → click Browse Image → select your file → connect Image output to Alpha Over top input",
    commonMistakes: [
      "Wrong color space — set to Linear for EXR/HDR, sRGB for JPEGs",
      "Frame range not set for sequences — the node shows frame 1 only",
    ],
    performanceTips: ["For large images used repeatedly, enable caching in the compositor preferences"],
    relatedNodes: ["comp-render-layers", "comp-alpha-over", "comp-composite"],
    frequentlyUsedWith: ["comp-alpha-over", "comp-scale"],
    screenshotPlaceholder: "Image node with a photo loaded, showing Image and Alpha outputs",
    quiz: [{ question: "What color space should you use when loading a JPEG photograph?", answer: "sRGB, since JPEGs store colors in sRGB space." }],
    practiceExercise: "Load a background photo and composite your 3D render on top of it using an Alpha Over node.",
    blenderVersion: "4.4",
    lastVerified: "2025-03",
    tags: ["image", "input", "photo", "plate", "exr", "sequence"],
  },

  // ── OUTPUT ──────────────────────────────────────────────────────────────────

  {
    id: "comp-composite",
    name: "Composite",
    category: "compositor-nodes",
    subcategory: "Output",
    icon: "📤",
    color: "green",
    description: "The final output node — the compositor writes whatever is connected here to the render result.",
    whyItExists: "Every compositor tree needs an endpoint. This is it.",
    whenToUse: "Always — connect your final composited image here.",
    inputs: [
      { name: "Image", type: "Color", description: "The final composited image to output" },
      { name: "Alpha", type: "Float", description: "Alpha channel override", default: "1.0" },
      { name: "Z", type: "Float", description: "Depth buffer output" },
    ],
    outputs: [],
    beginnerExplanation: "Think of it as the Save button — whatever you plug in here becomes the final image you see in the Image Editor.",
    advancedExplanation: "When 'Use Node' is enabled in the compositor, this node controls what Blender shows as the render result and what gets written to disk on Save. Only one Composite node can be active at a time.",
    commonUseCases: [
      "Final output of every compositor pipeline",
      "Connecting color-graded result for rendering to disk",
    ],
    typicalConnections: ["Color Balance", "→", "Composite"],
    exampleWorkflow: "Connect your last processing node's Image output → Composite node input",
    commonMistakes: [
      "Forgetting to connect anything — the render result stays unprocessed",
      "Having multiple Composite nodes — only the last one is used",
    ],
    performanceTips: ["Disable compositor effects during animation preview for faster playback — re-enable before final render"],
    relatedNodes: ["comp-viewer", "comp-render-layers"],
    frequentlyUsedWith: ["comp-color-balance", "comp-glare", "comp-render-layers"],
    screenshotPlaceholder: "Composite node connected to the end of a compositor node tree",
    quiz: [{ question: "What setting must be ON in the compositor header for this node to take effect?", answer: "Use Nodes must be enabled in the compositor header." }],
    practiceExercise: "Build a simple color correction: Render Layers → Bright/Contrast → Composite.",
    blenderVersion: "4.4",
    lastVerified: "2025-03",
    tags: ["output", "composite", "render", "final"],
  },

  {
    id: "comp-viewer",
    name: "Viewer",
    category: "compositor-nodes",
    subcategory: "Output",
    icon: "👁️",
    color: "green",
    description: "Preview any intermediate node output in the Image Editor without affecting the final render.",
    whyItExists: "Debugging compositor trees requires seeing intermediate results without routing them to the final output.",
    whenToUse: "When you want to check what a node is producing mid-tree, or A/B compare effects.",
    inputs: [
      { name: "Image", type: "Color", description: "The image to preview" },
      { name: "Alpha", type: "Float", description: "Alpha channel", default: "1.0" },
    ],
    outputs: [],
    beginnerExplanation: "A TV screen in the middle of your node tree — plug anything in to see it without changing the final output.",
    advancedExplanation: "Press Ctrl+Shift+Click on any node to route its output directly to the active Viewer node. The result shows in Image Editor → Viewer Node. Multiple Viewer nodes can exist but only the active one (highlighted) shows.",
    commonUseCases: [
      "Checking what a mask looks like mid-tree",
      "Comparing before/after a color grade",
      "Debugging why a blend effect looks wrong",
    ],
    typicalConnections: ["Glare", "→", "Viewer (preview)"],
    exampleWorkflow: "Ctrl+Shift+Click any node → its output appears in the Viewer instantly",
    commonMistakes: [
      "Using it instead of Composite for final output — Viewer doesn't save to disk",
      "Forgetting to switch the Image Editor to 'Viewer Node' mode",
    ],
    performanceTips: ["Use Ctrl+Shift+Click shortcut instead of manually routing cables to the Viewer"],
    relatedNodes: ["comp-composite"],
    frequentlyUsedWith: ["comp-glare", "comp-color-balance"],
    screenshotPlaceholder: "Viewer node with Ctrl+Shift+Click shortcut shown, Image Editor displaying the preview",
    quiz: [{ question: "What keyboard shortcut routes any node's output to the active Viewer?", answer: "Ctrl+Shift+Click on the node." }],
    practiceExercise: "In a compositor tree, Ctrl+Shift+Click three different nodes and observe how the preview changes.",
    blenderVersion: "4.4",
    lastVerified: "2025-03",
    tags: ["viewer", "preview", "debug", "output"],
  },

  // ── COLOR ──────────────────────────────────────────────────────────────────

  {
    id: "comp-color-balance",
    name: "Color Balance",
    category: "compositor-nodes",
    subcategory: "Color",
    icon: "🎨",
    color: "yellow",
    description: "Adjusts shadows, midtones, and highlights with separate color controls — the primary color grading node.",
    whyItExists: "Professional color grading requires independent control of the three tonal ranges. This is the film industry standard approach.",
    whenToUse: "For color grading your final render — to push shadows cooler, warm highlights, etc.",
    inputs: [
      { name: "Factor", type: "Float", description: "Blend factor between original and graded", default: "1.0" },
      { name: "Image", type: "Color", description: "Image to color grade" },
    ],
    outputs: [
      { name: "Image", type: "Color", description: "Color graded result" },
    ],
    beginnerExplanation: "Three color wheels: one for darks, one for grays, one for brights. Spin them to change the color mood of your render.",
    advancedExplanation: "Two modes: Lift/Gamma/Gain (broadcast standard) and ASC CDL (film standard). Lift = shadows offset, Gamma = midtone power curve, Gain = highlight scale. In CDL mode: Slope = contrast, Offset = lift, Power = gamma.",
    commonUseCases: [
      "Making shadows cooler (blue) and highlights warmer (orange) — cinematic look",
      "Fixing color casts from improper lighting",
      "Matching two renders to the same color grade",
    ],
    typicalConnections: ["Render Layers", "→", "Color Balance", "→", "Composite"],
    exampleWorkflow: "Connect Render Layers → Color Balance → Composite → adjust Lift toward blue, Gain toward warm orange",
    commonMistakes: [
      "Over-saturating — start with subtle adjustments",
      "Grading before noise reduction — grade after Denoise",
    ],
    performanceTips: ["Use Factor input to blend the effect — keeps original accessible for A/B comparison"],
    relatedNodes: ["comp-hue-saturation-value", "comp-bright-contrast", "comp-curves"],
    frequentlyUsedWith: ["comp-glare", "comp-render-layers", "comp-vignette"],
    screenshotPlaceholder: "Color Balance node with Lift/Gamma/Gain color wheels, example of cinematic grade",
    quiz: [{ question: "Which tonal range does the 'Lift' control affect?", answer: "Shadows (dark tones)." }],
    practiceExercise: "Apply a teal-and-orange grade: push Lift toward cyan-blue and Gain toward warm orange.",
    blenderVersion: "4.4",
    lastVerified: "2025-03",
    tags: ["color", "grade", "lift", "gamma", "gain", "shadows", "highlights"],
  },

  {
    id: "comp-hue-saturation-value",
    name: "Hue Saturation Value",
    category: "compositor-nodes",
    subcategory: "Color",
    icon: "🌈",
    color: "yellow",
    description: "Shifts hue, adjusts saturation, and changes value (brightness) of an image.",
    whyItExists: "Sometimes you need to change the dominant color or punch up saturation without affecting contrast.",
    whenToUse: "When the overall image looks right but the colors need a shift or desaturation.",
    inputs: [
      { name: "Image", type: "Color", description: "Input image" },
      { name: "Hue", type: "Float", description: "Hue shift (0-1, where 0.5 = no shift)", default: "0.5" },
      { name: "Saturation", type: "Float", description: "Saturation multiplier", default: "1.0" },
      { name: "Value", type: "Float", description: "Brightness multiplier", default: "1.0" },
      { name: "Factor", type: "Float", description: "Blend with original", default: "1.0" },
    ],
    outputs: [
      { name: "Image", type: "Color", description: "Adjusted image" },
    ],
    beginnerExplanation: "Hue = what color it is, Saturation = how colorful, Value = how bright. Simple sliders for each.",
    advancedExplanation: "Hue is a full 0-1 cycle where 0.5 = no change, 0 or 1 = 180° shift. Saturation at 0 = full desaturation (black and white). Unlike Color Balance, this doesn't target tonal ranges — it applies globally.",
    commonUseCases: [
      "Desaturating a render to check composition/values before adding color",
      "Shifting overall hue when a scene reads too warm or cool",
      "Boosting saturation for a more vivid look",
    ],
    typicalConnections: ["Render Layers", "→", "Hue Saturation Value", "→", "Color Balance", "→", "Composite"],
    exampleWorkflow: "Add HSV node after Render Layers → reduce Saturation to 0.8 → use Factor to blend in the effect",
    commonMistakes: [
      "Using Hue 0.0 thinking it does nothing — 0.0 and 0.5 are the same no-change value (it's a cycle)",
      "Maxing out Saturation — causes color banding in skies",
    ],
    performanceTips: ["Process this before more expensive effects like Glare or blur"],
    relatedNodes: ["comp-color-balance", "comp-bright-contrast", "comp-curves"],
    frequentlyUsedWith: ["comp-color-balance"],
    screenshotPlaceholder: "Hue Saturation Value node with reduced saturation for stylized look",
    quiz: [{ question: "What Hue value means no change?", answer: "0.5 — it's the center of the 0–1 hue cycle." }],
    practiceExercise: "Desaturate your render to 0.0, then use Factor to blend back in 30% of the original color.",
    blenderVersion: "4.4",
    lastVerified: "2025-03",
    tags: ["hue", "saturation", "value", "color", "desaturate"],
  },

  {
    id: "comp-curves",
    name: "RGB Curves",
    category: "compositor-nodes",
    subcategory: "Color",
    icon: "📈",
    color: "yellow",
    description: "Fine-tunes color and luminance using curves for each channel (R, G, B, and composite).",
    whyItExists: "Curves give the most precise tonal control — you can adjust any range independently with multiple control points.",
    whenToUse: "For nuanced color grading, fixing color channel imbalances, or creating stylized contrast.",
    inputs: [
      { name: "Factor", type: "Float", description: "Blend with original", default: "1.0" },
      { name: "Image", type: "Color", description: "Image to adjust" },
      { name: "Black Level", type: "Color", description: "Defines the black point" },
      { name: "White Level", type: "Color", description: "Defines the white point" },
    ],
    outputs: [
      { name: "Image", type: "Color", description: "Adjusted image" },
    ],
    beginnerExplanation: "Drag a line that goes from black to white — bowing it up makes things brighter, down makes them darker. You can do this for each color separately.",
    advancedExplanation: "Each channel (C/R/G/B) has an independent Bézier curve from input (X) to output (Y). Multiple control points allow S-curves for contrast, lowered blacks for film look, or per-channel grading for color correction.",
    commonUseCases: [
      "S-curve for contrast boost while preserving shadow detail",
      "Lifting the black point for a 'faded film' look",
      "Reducing green channel to make a scene cooler/more teal",
    ],
    typicalConnections: ["Color Balance", "→", "RGB Curves", "→", "Composite"],
    exampleWorkflow: "Add Curves after Color Balance → select C channel → pull center slightly up for contrast → fine-tune R/G/B channels for color cast",
    commonMistakes: [
      "Adding too many control points — hard to manage and creates unexpected bumps",
      "Clipping highlights by pulling the top right point too high",
    ],
    performanceTips: ["Keep curve shapes smooth — sharp corners create color posterization"],
    relatedNodes: ["comp-color-balance", "comp-hue-saturation-value"],
    frequentlyUsedWith: ["comp-color-balance", "comp-render-layers"],
    screenshotPlaceholder: "RGB Curves node with S-curve on C channel for cinematic contrast",
    quiz: [{ question: "What does pulling the bottom-left point up in the C channel achieve?", answer: "It lifts the blacks — the darkest shadows are no longer pure black (creates a faded/film look)." }],
    practiceExercise: "Create an S-curve on the C channel: pull the lower quarter down slightly and the upper quarter up.",
    blenderVersion: "4.4",
    lastVerified: "2025-03",
    tags: ["curves", "color", "rgb", "contrast", "grade"],
  },

  // ── FILTER ─────────────────────────────────────────────────────────────────

  {
    id: "comp-glare",
    name: "Glare",
    category: "compositor-nodes",
    subcategory: "Filter",
    icon: "✨",
    color: "orange",
    description: "Adds bloom, streaks, fog glow, and lens flare effects to bright areas of an image.",
    whyItExists: "Real camera lenses scatter light from bright spots — this replicates that optical phenomenon.",
    whenToUse: "On renders with bright light sources, emissive materials, or reflections to add cinematic realism.",
    inputs: [
      { name: "Image", type: "Color", description: "Image to add glare to" },
    ],
    outputs: [
      { name: "Image", type: "Color", description: "Image with glare applied" },
    ],
    beginnerExplanation: "Makes bright things glow and sparkle, just like how a car headlight looks through a real camera.",
    advancedExplanation: "Four modes: Bloom (soft glow around bright areas), Streaks (anamorphic lens streaks), Fog Glow (wide diffuse light bleed), Ghosts (lens ghost artifacts). Threshold controls which pixels are bright enough to generate glare. Higher Quality = more accurate but slower.",
    commonUseCases: [
      "Bloom on neon signs, emissive materials, windows",
      "Star streaks on specular highlights for stylized look",
      "Anamorphic horizontal streaks for cinematic feel",
    ],
    typicalConnections: ["Render Layers", "→", "Glare", "→", "Lens Distortion", "→", "Composite"],
    exampleWorkflow: "Add Glare → set Type: Bloom → raise Threshold to ~0.8 → adjust Size and Strength → connect to Composite",
    commonMistakes: [
      "Threshold too low — glare appears on everything, not just bright spots",
      "Using Glare before a Denoise node — glare on noise looks terrible",
    ],
    performanceTips: [
      "Set Quality to Low during preview, High for final render only",
      "Glare is expensive — use sparingly and last in the chain",
    ],
    relatedNodes: ["comp-lens-distortion", "comp-render-layers", "comp-composite"],
    frequentlyUsedWith: ["comp-color-balance", "comp-render-layers"],
    screenshotPlaceholder: "Glare node with Bloom mode showing glow on bright emissive materials in render",
    quiz: [{ question: "What does the Threshold control in Glare?", answer: "The minimum brightness a pixel must have to generate glare — only brighter pixels are affected." }],
    practiceExercise: "Apply Glare with Streaks mode to a render with strong lighting and adjust the Angle Offset to rotate the streaks.",
    blenderVersion: "4.4",
    lastVerified: "2025-03",
    tags: ["glare", "bloom", "glow", "streaks", "lens", "light", "cinematic"],
  },

  {
    id: "comp-denoise",
    name: "Denoise",
    category: "compositor-nodes",
    subcategory: "Filter",
    icon: "🔇",
    color: "blue",
    description: "Removes noise from Cycles renders using AI-based denoising (Intel Open Image Denoise).",
    whyItExists: "Cycles is a path tracer — low sample counts produce noisy renders. Denoising recovers a clean image from fewer samples.",
    whenToUse: "On any Cycles render, especially animations where sample counts must be kept low.",
    inputs: [
      { name: "Image", type: "Color", description: "Noisy render image" },
      { name: "Normal", type: "Vector", description: "Denoising normal pass (enables better edge preservation)" },
      { name: "Albedo", type: "Color", description: "Denoising albedo pass (preserves texture detail)" },
    ],
    outputs: [
      { name: "Image", type: "Color", description: "Denoised image" },
    ],
    beginnerExplanation: "AI cleans up the grainy look from low-sample Cycles renders automatically.",
    advancedExplanation: "Uses Intel OIDN. For best quality: enable Denoising Data passes in View Layer, connect Normal and Albedo inputs. Without those passes the denoiser works on color only and can smear details. Should be the FIRST node after Render Layers, before any color grading.",
    commonUseCases: [
      "Cleaning up animation frames rendered at 64–128 samples",
      "Removing fireflies (bright noise specks)",
      "Reducing render time by using fewer samples with denoising",
    ],
    typicalConnections: ["Render Layers", "→", "Denoise", "→", "Color Balance", "→", "Composite"],
    exampleWorkflow: "Enable View Layer → Denoising Data → render → connect Render Layers Image/Normal/Albedo to Denoise inputs → connect output to color grade",
    commonMistakes: [
      "Placing Denoise after color grading — grade first, then denoise smears the color",
      "Not enabling Denoising Data passes — the node still works but less accurately",
    ],
    performanceTips: [
      "Place Denoise immediately after Render Layers before any other processing",
      "Use per-layer denoising in render settings instead for animation (faster)",
    ],
    relatedNodes: ["comp-render-layers", "comp-composite", "comp-glare"],
    frequentlyUsedWith: ["comp-render-layers", "comp-color-balance"],
    screenshotPlaceholder: "Denoise node connected to Render Layers with Normal and Albedo passes, before/after comparison",
    quiz: [{ question: "Where should the Denoise node be placed in the node tree?", answer: "Immediately after Render Layers, before color grading or effects." }],
    practiceExercise: "Enable Denoising Data passes, render at 32 samples, and compare denoised vs raw output.",
    blenderVersion: "4.4",
    lastVerified: "2025-03",
    tags: ["denoise", "noise", "cycles", "oidn", "ai", "clean"],
  },

  {
    id: "comp-blur",
    name: "Blur",
    category: "compositor-nodes",
    subcategory: "Filter",
    icon: "💨",
    color: "blue",
    description: "Applies a blur (Gaussian, Box, or other algorithms) to an image.",
    whyItExists: "Blurring is fundamental to many effects — depth of field simulation, glows, soft masks, motion blur.",
    whenToUse: "Whenever you need to soften an image, create a glow base, or blur a matte.",
    inputs: [
      { name: "Image", type: "Color", description: "Image to blur" },
      { name: "Size", type: "Float", description: "Override for blur radius", default: "1.0" },
    ],
    outputs: [
      { name: "Image", type: "Color", description: "Blurred image" },
    ],
    beginnerExplanation: "Makes things fuzzy. Control X and Y blur amounts separately in the node settings.",
    advancedExplanation: "Multiple blur types: Gaussian (smooth, realistic), Box (fast), Catrom (sharp edge preservation), Fast Gaussian (cheaper). Relative mode scales blur amount to image resolution. Can blur X and Y independently for anisotropic (directional) blur.",
    commonUseCases: [
      "Pre-blurring for bloom effect base (before mixing with original)",
      "Softening a noise-based mask",
      "Creating depth of field with a Z-blur setup",
    ],
    typicalConnections: ["Render Layers", "→", "Blur", "→", "Mix (Add)", "→", "Composite"],
    exampleWorkflow: "For bloom: Render Layers → Blur (Gaussian, X:15 Y:15) → Mix (Add, 0.3) with original → Composite",
    commonMistakes: [
      "Using Box blur for smooth effects — it creates a visible square pattern",
      "Blur on the wrong layer — blur only the glow copy, not the full image",
    ],
    performanceTips: ["Fast Gaussian is significantly cheaper; use for previewing then switch to Gaussian for final"],
    relatedNodes: ["comp-glare", "comp-mix", "comp-bokeh-blur"],
    frequentlyUsedWith: ["comp-mix", "comp-render-layers"],
    screenshotPlaceholder: "Blur node with Gaussian mode, X and Y radius set for soft glow effect",
    quiz: [{ question: "Which blur type creates the smoothest result?", answer: "Gaussian — it creates a natural, smooth falloff." }],
    practiceExercise: "Duplicate a render, blur one copy heavily, then mix it back with the original at 0.3 factor for a glow effect.",
    blenderVersion: "4.4",
    lastVerified: "2025-03",
    tags: ["blur", "gaussian", "filter", "glow", "soften"],
  },

  // ── MATTE ──────────────────────────────────────────────────────────────────

  {
    id: "comp-alpha-over",
    name: "Alpha Over",
    category: "compositor-nodes",
    subcategory: "Matte",
    icon: "🔲",
    color: "purple",
    description: "Composites one image over another using alpha transparency — the core compositing operation.",
    whyItExists: "The fundamental 'over' operation in compositing (Porter-Duff): places image A on top of image B using A's alpha.",
    whenToUse: "Whenever combining a foreground element (with alpha) over a background.",
    inputs: [
      { name: "Factor", type: "Float", description: "Blend amount for the composite", default: "1.0" },
      { name: "Image (bottom)", type: "Color", description: "Background image" },
      { name: "Image (top)", type: "Color", description: "Foreground image (uses its own alpha)" },
    ],
    outputs: [
      { name: "Image", type: "Color", description: "Composited result" },
    ],
    beginnerExplanation: "Stack two images — the top one goes over the bottom wherever the top has color. Where the top is transparent, the bottom shows through.",
    advancedExplanation: "Implements the standard Porter-Duff 'over' composite operation. Top input's alpha determines blend. 'Use Straight Alpha' checkbox matters when working with premultiplied vs. straight alpha images. For multiple layers, chain multiple Alpha Over nodes.",
    commonUseCases: [
      "Compositing a 3D render (with background removed) onto a photo plate",
      "Layering multiple render elements together",
      "Placing a title graphic with alpha over a video",
    ],
    typicalConnections: ["Image (background)", "→", "Alpha Over", "←", "Render (foreground)", "→", "Composite"],
    exampleWorkflow: "Load background image → connect to bottom Alpha Over input → connect render to top input → connect output to Composite",
    commonMistakes: [
      "Connecting images to the wrong inputs — top goes over bottom, not the other way",
      "Black fringing around edges — switch between premultiplied/straight alpha modes",
    ],
    performanceTips: ["Chain multiple Alpha Over nodes left to right for layered compositing"],
    relatedNodes: ["comp-mix", "comp-image", "comp-render-layers"],
    frequentlyUsedWith: ["comp-image", "comp-render-layers"],
    screenshotPlaceholder: "Alpha Over node stacking a 3D render over a background photo plate",
    quiz: [{ question: "Which input is the foreground (goes on top)?", answer: "The second Image input — the one labeled 'top' or connected last." }],
    practiceExercise: "Load a background photo and composite your render over it with Alpha Over.",
    blenderVersion: "4.4",
    lastVerified: "2025-03",
    tags: ["alpha", "over", "composite", "layer", "transparency", "keying"],
  },

  // ── DISTORT ────────────────────────────────────────────────────────────────

  {
    id: "comp-lens-distortion",
    name: "Lens Distortion",
    category: "compositor-nodes",
    subcategory: "Distort",
    icon: "🔭",
    color: "purple",
    description: "Simulates real camera lens distortion including barrel distortion, chromatic aberration, and vignette.",
    whyItExists: "Real camera lenses distort and aberrate light — adding these artifacts makes CG renders look more photographic.",
    whenToUse: "On final renders you want to look like they came from a real camera.",
    inputs: [
      { name: "Image", type: "Color", description: "Image to distort" },
      { name: "Distort", type: "Float", description: "Barrel/pincushion amount", default: "0.0" },
      { name: "Dispersion", type: "Float", description: "Chromatic aberration amount", default: "0.0" },
    ],
    outputs: [
      { name: "Image", type: "Color", description: "Distorted image" },
    ],
    beginnerExplanation: "Makes your CG render look like it was filmed by a real camera — slightly warped edges and color fringing.",
    advancedExplanation: "Distort: positive = barrel (edges bow out), negative = pincushion (edges bow in). Dispersion adds chromatic aberration by splitting RGB channels at edges. Projector mode maps correctly for projector lens characteristics. Jitter mode adds sub-pixel sampling for anti-aliased distortion.",
    commonUseCases: [
      "Adding realism to architectural visualization renders",
      "Matching a CG render to a real footage plate's lens characteristics",
      "Adding chromatic aberration for stylized cyberpunk/photo look",
    ],
    typicalConnections: ["Glare", "→", "Lens Distortion", "→", "Composite"],
    exampleWorkflow: "After all color grading → add Lens Distortion → set Distort to 0.05 (subtle barrel) → Dispersion 0.01 for fringing",
    commonMistakes: [
      "Too much distortion — subtle values (0.02–0.05) look realistic; higher values look like a fisheye",
      "Adding Dispersion before denoising — chromatic aberration on noise looks terrible",
    ],
    performanceTips: ["Apply Lens Distortion last in the chain — it's cheap and doesn't affect upstream processing"],
    relatedNodes: ["comp-glare", "comp-composite"],
    frequentlyUsedWith: ["comp-glare", "comp-color-balance"],
    screenshotPlaceholder: "Lens Distortion node with subtle barrel distortion and chromatic aberration on render",
    quiz: [{ question: "What does a positive Distort value create?", answer: "Barrel distortion — edges bow outward, like a wide-angle lens." }],
    practiceExercise: "Apply Lens Distortion with Distort: 0.03 and Dispersion: 0.01 to a render and compare with the original.",
    blenderVersion: "4.4",
    lastVerified: "2025-03",
    tags: ["lens", "distortion", "aberration", "chromatic", "barrel", "camera"],
  },

  // ── UTILITIES ──────────────────────────────────────────────────────────────

  {
    id: "comp-mix",
    name: "Mix",
    category: "compositor-nodes",
    subcategory: "Color",
    icon: "🔀",
    color: "yellow",
    description: "Blends two images using standard blend modes (Add, Multiply, Screen, Overlay, etc.).",
    whyItExists: "Blend modes are essential for combining render passes, creating effects, and building composite layers.",
    whenToUse: "Any time you need to combine two images with a specific blend operation.",
    inputs: [
      { name: "Factor", type: "Float", description: "Blend amount", default: "0.5" },
      { name: "Image (A)", type: "Color", description: "First image" },
      { name: "Image (B)", type: "Color", description: "Second image" },
    ],
    outputs: [
      { name: "Image", type: "Color", description: "Blended result" },
    ],
    beginnerExplanation: "Like Photoshop blend modes — Add makes things brighter, Multiply makes them darker, Screen creates glow.",
    advancedExplanation: "Supports all standard blend modes. Key ones: Add (great for glows and emission), Multiply (masks and darkening), Screen (non-destructive brightening), Overlay (contrast boost while mixing), Mix (linear interpolation). Clamp option prevents out-of-range values.",
    commonUseCases: [
      "Screen mode for adding a glare pass back onto the render",
      "Multiply mode for applying a dirt/vignette mask",
      "Add mode for combining emission and beauty passes",
    ],
    typicalConnections: ["Blur", "→", "Mix (Screen)", "←", "Render Layers", "→", "Composite"],
    exampleWorkflow: "Duplicate signal: one → Blur → second input of Mix (Screen mode, Factor 0.4) with original as first input",
    commonMistakes: [
      "Using Add at Factor 1.0 on non-emission passes — blows out highlights",
      "Forgetting Clamp when values go over 1.0 and look broken downstream",
    ],
    performanceTips: ["Mix is extremely fast — no reason to avoid it for multiple blend operations"],
    relatedNodes: ["comp-alpha-over", "comp-blur", "comp-glare"],
    frequentlyUsedWith: ["comp-blur", "comp-glare", "comp-render-layers"],
    screenshotPlaceholder: "Mix node in Screen mode combining a blurred glow pass with the original render",
    quiz: [{ question: "What does Screen blend mode do?", answer: "Brightens by inverting both images, multiplying them, then inverting the result — creates non-destructive brightening and glow." }],
    practiceExercise: "Create a bloom: blur your render heavily, then Mix (Screen) it back onto the original at 0.3 Factor.",
    blenderVersion: "4.4",
    lastVerified: "2025-03",
    tags: ["mix", "blend", "screen", "add", "multiply", "overlay", "combine"],
  },

  {
    id: "comp-bright-contrast",
    name: "Bright/Contrast",
    category: "compositor-nodes",
    subcategory: "Color",
    icon: "☀️",
    color: "yellow",
    description: "Adjusts overall brightness and contrast of an image with simple numeric controls.",
    whyItExists: "Quick luminance adjustments without the complexity of curves or color balance.",
    whenToUse: "For fast brightness/contrast tweaks when you don't need per-channel control.",
    inputs: [
      { name: "Image", type: "Color", description: "Image to adjust" },
      { name: "Bright", type: "Float", description: "Brightness offset (positive = brighter)", default: "0.0" },
      { name: "Contrast", type: "Float", description: "Contrast multiplier", default: "0.0" },
    ],
    outputs: [
      { name: "Image", type: "Color", description: "Adjusted image" },
    ],
    beginnerExplanation: "Two sliders: one makes the image lighter or darker, one makes darks darker and lights lighter.",
    advancedExplanation: "Bright adds a linear offset to all pixel values. Contrast applies a linear contrast around the 0.5 midpoint. 'Use Legacy' mode uses an older algorithm with clipping. For precise control, RGB Curves is preferred.",
    commonUseCases: [
      "Quick exposure fix when a render looks too dark",
      "Punching contrast before color grading",
    ],
    typicalConnections: ["Render Layers", "→", "Bright/Contrast", "→", "Color Balance", "→", "Composite"],
    exampleWorkflow: "Add Bright/Contrast early in chain → adjust Bright to fix exposure → Color Balance for grading",
    commonMistakes: [
      "Using large Bright values instead of proper exposure — causes harsh clipping",
      "Not using 'Convert Premultiplied' when alpha fringing appears",
    ],
    performanceTips: ["This is the fastest way to adjust luminance — extremely cheap computationally"],
    relatedNodes: ["comp-curves", "comp-color-balance", "comp-hue-saturation-value"],
    frequentlyUsedWith: ["comp-color-balance"],
    screenshotPlaceholder: "Bright/Contrast node with Bright adjusted to fix underexposed render",
    quiz: [{ question: "Around what value does Contrast adjustment happen?", answer: "0.5 (the midpoint) — values above 0.5 get brighter, below get darker." }],
    practiceExercise: "Fix a deliberately dark render using only Bright/Contrast — aim for correct exposure before grading.",
    blenderVersion: "4.4",
    lastVerified: "2025-03",
    tags: ["brightness", "contrast", "luminance", "exposure"],
  },

];

export const COMPOSITOR_NODE_INDEX = COMPOSITOR_NODES.map(n => ({
  id: n.id,
  name: n.name,
  category: n.category,
  subcategory: n.subcategory,
  icon: n.icon,
  color: n.color,
  description: n.description,
  tags: n.tags,
}));

export const COMPOSITOR_NODE_MAP = Object.fromEntries(
  COMPOSITOR_NODES.map(n => [n.id, n])
);
