// Maps our node IDs to Blender Python class names so we can build official docs image URLs.
// URL format: https://docs.blender.org/manual/en/latest/_images/node-types_{ClassName}.png
//
// To add a new node: find its Python class in Blender > Preferences > Developer Info,
// hover over the node in the Add menu — the class name appears in the tooltip.

export const NODE_CLASS_MAP: Record<string, string> = {
  // ── Geometry Nodes ────────────────────────────────────────────────────────
  "join-geometry":               "GeometryNodeJoinGeometry",
  "instance-on-points":          "GeometryNodeInstanceOnPoints",
  "distribute-points-on-faces":  "GeometryNodeDistributePointsOnFaces",
  "distribute-points-in-volume": "GeometryNodeDistributePointsInVolume",
  "set-position":                "GeometryNodeSetPosition",
  "merge-by-distance":           "GeometryNodeMergeByDistance",
  "realize-instances":           "GeometryNodeRealizeInstances",
  "transform-geometry":          "GeometryNodeTransform",
  "bounding-box":                "GeometryNodeBoundBox",
  "convex-hull":                 "GeometryNodeConvexHull",
  "delete-geometry":             "GeometryNodeDeleteGeometry",
  "separate-geometry":           "GeometryNodeSeparateGeometry",
  "separate-components":         "GeometryNodeSeparateComponents",
  "extrude-mesh":                "GeometryNodeExtrudeMesh",
  "mesh-boolean":                "GeometryNodeMeshBoolean",
  "subdivide-mesh":              "GeometryNodeSubdivideMesh",
  "triangulate":                 "GeometryNodeTriangulate",
  "flip-faces":                  "GeometryNodeFlipFaces",
  "split-edges":                 "GeometryNodeSplitEdges",
  "dual-mesh":                   "GeometryNodeDualMesh",
  "mesh-to-curve":               "GeometryNodeMeshToCurve",
  "mesh-to-points":              "GeometryNodeMeshToPoints",
  "mesh-to-volume":              "GeometryNodeMeshToVolume",
  "curve-to-mesh":               "GeometryNodeCurveToMesh",
  "curve-to-points":             "GeometryNodeCurveToPoints",
  "fill-curve":                  "GeometryNodeFillCurve",
  "fillet-curve":                "GeometryNodeFilletCurve",
  "resample-curve":              "GeometryNodeResampleCurve",
  "reverse-curve":               "GeometryNodeReverseCurve",
  "trim-curve":                  "GeometryNodeTrimCurve",
  "subdivide-curve":             "GeometryNodeSubdivideCurve",
  "interpolate-curves":          "GeometryNodeInterpolateCurves",
  "sample-curve":                "GeometryNodeSampleCurve",
  "set-curve-tilt":              "GeometryNodeSetCurveTilt",
  "set-spline-type":             "GeometryNodeCurveSplineType",
  "spline-length":               "GeometryNodeSplineLength",
  "spline-parameter":            "GeometryNodeSplineParameter",
  "curve-circle":                "GeometryNodeCurvePrimitiveCircle",
  "curve-arc":                   "GeometryNodeCurveArc",
  "curve-star":                  "GeometryNodeCurveStar",
  "curve-spiral":                "GeometryNodeCurveSpiral",
  "quadrilateral":               "GeometryNodeCurvePrimitiveQuadrilateral",
  "bezier-segment":              "GeometryNodeCurvePrimitiveBezierSegment",
  "points-to-vertices":          "GeometryNodePointsToVertices",
  "points-to-curves":            "GeometryNodePointsToCurves",
  "points-to-volume":            "GeometryNodePointsToVolume",
  "set-point-radius":            "GeometryNodeSetPointRadius",
  "string-to-curves":            "GeometryNodeStringToCurves",
  "value-to-string":             "FunctionNodeValueToString",
  "set-material":                "GeometryNodeSetMaterial",
  "replace-material":            "GeometryNodeReplaceMaterial",
  "set-material-index":          "GeometryNodeSetMaterialIndex",
  "capture-attribute":           "GeometryNodeCaptureAttribute",
  "store-named-attribute":       "GeometryNodeStoreNamedAttribute",
  "attribute-statistic":         "GeometryNodeAttributeStatistic",
  "domain-size":                 "GeometryNodeAttributeDomainSize",
  "blur-attribute":              "GeometryNodeBlurAttribute",
  "remove-named-attribute":      "GeometryNodeRemoveAttribute",
  "named-attribute":             "GeometryNodeInputNamedAttribute",
  "sample-index":                "GeometryNodeSampleIndex",
  "sample-nearest":              "GeometryNodeSampleNearest",
  "geometry-proximity":          "GeometryNodeProximity",
  "raycast":                     "GeometryNodeRaycast",
  "geometry-to-instance":        "GeometryNodeGeometryToInstance",
  "instances-to-points":         "GeometryNodeInstancesToPoints",
  "rotate-instances":            "GeometryNodeRotateInstances",
  "scale-instances":             "GeometryNodeScaleInstances",
  "translate-instances":         "GeometryNodeTranslateInstances",
  "scale-elements":              "GeometryNodeScaleElements",
  "uv-unwrap":                   "GeometryNodeUVUnwrap",
  "pack-uv-islands":             "GeometryNodeUVPackIslands",
  "volume-to-mesh":              "GeometryNodeVolumeToMesh",
  "volume-cube":                 "GeometryNodeVolumeCube",
  "mesh-cone":                   "GeometryNodeMeshCone",
  "mesh-cube":                   "GeometryNodeMeshCube",
  "mesh-cylinder":               "GeometryNodeMeshCylinder",
  "mesh-grid":                   "GeometryNodeMeshGrid",
  "mesh-ico-sphere":             "GeometryNodeMeshIcoSphere",
  "mesh-uv-sphere":              "GeometryNodeMeshUVSphere",
  "mesh-circle":                 "GeometryNodeMeshCircle",
  "mesh-line":                   "GeometryNodeMeshLine",
  "set-shade-smooth":            "GeometryNodeSetShadeSmooth",
  "edge-paths-to-curves":        "GeometryNodeEdgePathsToCurves",
  "noise-texture":               "GeometryNodeTexNoise",
  "voronoi-texture":             "GeometryNodeTexVoronoi",
  "wave-texture":                "GeometryNodeTexWave",
  "gradient-texture":            "GeometryNodeTexGradient",
  "magic-texture":               "GeometryNodeTexMagic",
  "white-noise-texture":         "GeometryNodeTexWhiteNoise",
  "checker-texture":             "GeometryNodeTexChecker",
  "image-texture-geo":           "GeometryNodeImageTexture",
  "math-geo":                    "ShaderNodeMath",
  "boolean-math":                "FunctionNodeBooleanMath",
  "integer-math":                "FunctionNodeIntegerMath",
  "clamp-geo":                   "ShaderNodeClamp",
  "map-range-geo":               "ShaderNodeMapRange",
  "switch":                      "GeometryNodeSwitch",
  "index-switch":                "GeometryNodeIndexSwitch",
  "field-at-index":              "GeometryNodeFieldAtIndex",
  "accumulate-field":            "GeometryNodeAccumulateField",
  "align-euler-to-vector":       "FunctionNodeAlignEulerToVector",
  "rotate-euler":                "FunctionNodeRotateEuler",
  "combine-xyz":                 "ShaderNodeCombineXYZ",
  "separate-xyz":                "ShaderNodeSeparateXYZ",
  "object-info":                 "GeometryNodeObjectInfo",
  "collection-info":             "GeometryNodeCollectionInfo",
  "scene-time":                  "GeometryNodeInputSceneTime",
  "is-viewport":                 "GeometryNodeIsViewport",
  "color-ramp-geo":              "ShaderNodeValToRGB",
  "float-curve":                 "ShaderNodeFloatCurve",
  "compare":                     "FunctionNodeCompare",

  // ── Shader Nodes ──────────────────────────────────────────────────────────
  "principled-bsdf":             "ShaderNodeBsdfPrincipled",
  "diffuse-bsdf":                "ShaderNodeBsdfDiffuse",
  "glossy-bsdf":                 "ShaderNodeBsdfGlossy",
  "glass-bsdf":                  "ShaderNodeBsdfGlass",
  "transparent-bsdf":            "ShaderNodeBsdfTransparent",
  "translucent-bsdf":            "ShaderNodeBsdfTranslucent",
  "refraction-bsdf":             "ShaderNodeBsdfRefraction",
  "velvet-bsdf":                 "ShaderNodeBsdfVelvet",
  "toon-bsdf":                   "ShaderNodeBsdfToon",
  "subsurface-scattering":       "ShaderNodeSubsurfaceScattering",
  "emission":                    "ShaderNodeEmission",
  "holdout":                     "ShaderNodeHoldout",
  "mix-shader":                  "ShaderNodeMixShader",
  "add-shader":                  "ShaderNodeAddShader",
  "volume-absorption":           "ShaderNodeVolumeAbsorption",
  "volume-scatter":              "ShaderNodeVolumeScatter",
  "principled-volume":           "ShaderNodeVolumePrincipled",
  "principled-hair-bsdf":        "ShaderNodeBsdfHairPrincipled",
  "hair-bsdf":                   "ShaderNodeBsdfHair",
  "image-texture":               "ShaderNodeTexImage",
  "environment-texture":         "ShaderNodeTexEnvironment",
  "sky-texture":                 "ShaderNodeTexSky",
  "shader-noise-texture":        "ShaderNodeTexNoise",
  "shader-voronoi-texture":      "ShaderNodeTexVoronoi",
  "shader-wave-texture":         "ShaderNodeTexWave",
  "shader-gradient-texture":     "ShaderNodeTexGradient",
  "shader-magic-texture":        "ShaderNodeTexMagic",
  "checker-texture-shader":      "ShaderNodeTexChecker",
  "brick-texture":               "ShaderNodeTexBrick",
  "ies-texture":                 "ShaderNodeTexIES",
  "point-density":               "ShaderNodeTexPointDensity",
  "musgrave-texture":            "ShaderNodeTexMusgrave",
  "color-ramp":                  "ShaderNodeValToRGB",
  "rgb-curves":                  "ShaderNodeRGBCurve",
  "mix-rgb":                     "ShaderNodeMixRGB",
  "hue-saturation":              "ShaderNodeHueSaturation",
  "brightness-contrast":         "ShaderNodeBrightContrast",
  "gamma":                       "ShaderNodeGamma",
  "invert":                      "ShaderNodeInvert",
  "light-falloff":               "ShaderNodeLightFalloff",
  "math":                        "ShaderNodeMath",
  "vector-math":                 "ShaderNodeVectorMath",
  "vector-rotate":               "ShaderNodeVectorRotate",
  "vector-curves":               "ShaderNodeVectorCurve",
  "mapping":                     "ShaderNodeMapping",
  "texture-coordinate":          "ShaderNodeTexCoord",
  "uv-map":                      "ShaderNodeUVMap",
  "normal-map":                  "ShaderNodeNormalMap",
  "bump":                        "ShaderNodeBump",
  "displacement":                "ShaderNodeDisplacement",
  "vector-displacement":         "ShaderNodeVectorDisplacement",
  "normal":                      "ShaderNodeNormal",
  "fresnel":                     "ShaderNodeFresnel",
  "layer-weight":                "ShaderNodeLayerWeight",
  "light-path":                  "ShaderNodeLightPath",
  "ambient-occlusion":           "ShaderNodeAmbientOcclusion",
  "bevel":                       "ShaderNodeBevel",
  "camera-data":                 "ShaderNodeCameraData",
  "geometry-shader":             "ShaderNodeNewGeometry",
  "hair-info":                   "ShaderNodeHairInfo",
  "object-info-shader":          "ShaderNodeObjectInfo",
  "particle-info":               "ShaderNodeParticleInfo",
  "tangent":                     "ShaderNodeTangent",
  "vertex-color":                "ShaderNodeVertexColor",
  "wireframe":                   "ShaderNodeWireframe",
  "rgb-to-bw":                   "ShaderNodeRGBToBW",
  "blackbody":                   "ShaderNodeBlackbody",
  "wavelength":                  "ShaderNodeWavelength",
  "clamp":                       "ShaderNodeClamp",
  "map-range":                   "ShaderNodeMapRange",
  "separate-rgb":                "ShaderNodeSeparateRGB",
  "combine-rgb":                 "ShaderNodeCombineRGB",
  "separate-xyz-shader":         "ShaderNodeSeparateXYZ",
  "combine-xyz-shader":          "ShaderNodeCombineXYZ",
  "separate-color":              "ShaderNodeSeparateColor",
  "combine-color":               "ShaderNodeCombineColor",
  "float-curve-shader":          "ShaderNodeFloatCurve",
  "value":                       "ShaderNodeValue",
  "rgb":                         "ShaderNodeRGB",

  // ── Compositor Nodes ──────────────────────────────────────────────────────
  "comp-render-layers":          "CompositorNodeRLayers",
  "comp-image":                  "CompositorNodeImage",
  "comp-composite":              "CompositorNodeComposite",
  "comp-viewer":                 "CompositorNodeViewer",
  "comp-color-balance":          "CompositorNodeColorBalance",
  "comp-hue-saturation-value":   "CompositorNodeHueSat",
  "comp-curves":                 "CompositorNodeCurveRGB",
  "comp-glare":                  "CompositorNodeGlare",
  "comp-denoise":                "CompositorNodeDenoise",
  "comp-blur":                   "CompositorNodeBlur",
  "comp-alpha-over":             "CompositorNodeAlphaOver",
  "comp-lens-distortion":        "CompositorNodeLensdist",
  "comp-mix":                    "CompositorNodeMixRGB",
  "comp-bright-contrast":        "CompositorNodeBrightContrast",
};

export function blenderNodeImageUrl(nodeId: string): string | null {
  const cls = NODE_CLASS_MAP[nodeId];
  if (!cls) return null;
  return `https://docs.blender.org/manual/en/latest/_images/node-types_${cls}.png`;
}

// Modifier docs image URL attempts
export function blenderModifierImageUrls(modifierId: string): string[] {
  // Try multiple patterns — Blender docs naming is inconsistent for modifiers
  const name = modifierId.replace(/-/g, "_");
  return [
    `https://docs.blender.org/manual/en/latest/_images/modeling_modifiers_${name}_panel.png`,
    `https://docs.blender.org/manual/en/latest/_images/modeling_modifiers-generate_${name}.png`,
    `https://docs.blender.org/manual/en/latest/_images/modeling_modifiers-deform_${name}.png`,
    `https://docs.blender.org/manual/en/latest/_images/modeling_modifiers-modify_${name}.png`,
  ];
}

// Editor screenshot attempts from Blender docs
export const EDITOR_IMAGE_URLS: Record<string, string[]> = {
  "3d-viewport": [
    "https://docs.blender.org/manual/en/latest/_images/editors_3dview_introduction_default-startup.png",
    "https://docs.blender.org/manual/en/latest/_images/editors_3dview_introduction_ui-overview.png",
  ],
  "shader-editor": [
    "https://docs.blender.org/manual/en/latest/_images/editors_shader-editor_introduction.png",
    "https://docs.blender.org/manual/en/latest/_images/render_shader-nodes_introduction.png",
  ],
  "geometry-node-editor": [
    "https://docs.blender.org/manual/en/latest/_images/modeling_geometry-nodes_introduction.png",
    "https://docs.blender.org/manual/en/latest/_images/editors_geometry-node-editor_introduction.png",
  ],
  "timeline": [
    "https://docs.blender.org/manual/en/latest/_images/editors_timeline_introduction.png",
  ],
  "graph-editor": [
    "https://docs.blender.org/manual/en/latest/_images/editors_graph-editor_introduction.png",
  ],
  "dope-sheet": [
    "https://docs.blender.org/manual/en/latest/_images/editors_dope-sheet_introduction.png",
  ],
  "outliner": [
    "https://docs.blender.org/manual/en/latest/_images/editors_outliner_introduction.png",
  ],
  "properties": [
    "https://docs.blender.org/manual/en/latest/_images/editors_properties_introduction.png",
  ],
  "uv-editor": [
    "https://docs.blender.org/manual/en/latest/_images/editors_uv_introduction.png",
  ],
  "compositor": [
    "https://docs.blender.org/manual/en/latest/_images/editors_compositor_introduction.png",
    "https://docs.blender.org/manual/en/latest/_images/compositing_introduction.png",
  ],
  "image-editor": [
    "https://docs.blender.org/manual/en/latest/_images/editors_image_introduction.png",
  ],
  "asset-browser": [
    "https://docs.blender.org/manual/en/latest/_images/editors_asset-browser_introduction.png",
  ],
  "spreadsheet": [
    "https://docs.blender.org/manual/en/latest/_images/editors_spreadsheet_introduction.png",
  ],
  "script-editor": [
    "https://docs.blender.org/manual/en/latest/_images/editors_text-editor_introduction.png",
  ],
  "nla-editor": [
    "https://docs.blender.org/manual/en/latest/_images/editors_nla_introduction.png",
  ],
};
