import type { BlenderEditor, EditorIndex } from "./types";

export const BLENDER_EDITORS: BlenderEditor[] = [

  {
    id: "3d-viewport",
    name: "3D Viewport",
    shortName: "Viewport",
    icon: "👁️",
    color: "blue",
    description: "The main 3D view where you work with objects, meshes, and animations.",
    purpose: "Primary workspace for all 3D modeling, rigging, sculpting, posing, and animation.",
    whatYouCanDo: [
      "Select, transform (move/rotate/scale) objects and geometry",
      "Model meshes in Edit Mode",
      "Sculpt organic shapes",
      "Set up and preview animations",
      "Arrange scene composition",
      "Preview materials and lighting in rendered view",
    ],
    keyAreas: [
      { name: "Header", location: "Top bar", description: "Mode selector (Object/Edit/Sculpt…), pivot point, snap settings, proportional editing toggle." },
      { name: "Toolbar (T)", location: "Left side", description: "Mode-specific tools: move, rotate, scale, box select, knife, extrude, etc." },
      { name: "N-Panel (N)", location: "Right side", description: "Item properties (location/rotation/scale), view settings, addon panels." },
      { name: "Viewport Overlays", location: "Top right", description: "Toggle wireframe, statistics, normals, grid display." },
      { name: "Viewport Shading", location: "Top right", description: "Switch between Solid, Material Preview, Rendered, and Wireframe modes." },
      { name: "Gizmo", location: "Top right corner", description: "XYZ orientation gizmo for view rotation." },
    ],
    beginnerExplanation: "This is where you build and animate everything. Click to select, G to grab (move), R to rotate, S to scale. Press Tab to toggle between Object Mode and Edit Mode.",
    advancedExplanation: "The viewport supports multiple shading engines (EEVEE, Cycles, Workbench). Viewport render sampling can be adjusted for quality. Quad view (Ctrl+Alt+Q) shows 4 simultaneous views. Local mode (/) isolates selected objects. ALT+Z toggles X-ray for seeing through meshes.",
    commonWorkflows: [
      "G/R/S → X/Y/Z to constrain transforms to an axis",
      "Alt+G/R/S to clear transforms",
      "Shift+D to duplicate objects",
      "Ctrl+L to select linked geometry",
      "H to hide, Alt+H to unhide",
      "/ to enter Local View (isolate selected)",
    ],
    shortcuts: [
      { key: "G", action: "Grab/Move", context: "Object/Edit Mode" },
      { key: "R", action: "Rotate", context: "Object/Edit Mode" },
      { key: "S", action: "Scale", context: "Object/Edit Mode" },
      { key: "Tab", action: "Toggle Object/Edit Mode" },
      { key: "A", action: "Select All / Deselect All" },
      { key: "H / Alt+H", action: "Hide / Unhide selected" },
      { key: "Shift+D", action: "Duplicate" },
      { key: "Ctrl+R", action: "Loop Cut (Edit Mode)" },
      { key: "E", action: "Extrude (Edit Mode)" },
      { key: "I", action: "Inset Faces (Edit Mode)" },
      { key: "Ctrl+B / B", action: "Bevel / Box Select" },
      { key: "Alt+Z", action: "X-Ray toggle" },
      { key: "Numpad 1/3/7", action: "Front/Right/Top orthographic view" },
      { key: "Numpad 5", action: "Toggle Perspective/Orthographic" },
      { key: "/", action: "Local View (isolate)" },
      { key: "Z", action: "Shading pie menu" },
    ],
    tips: [
      "Middle Mouse drag to orbit, Shift+Middle Mouse to pan, scroll to zoom.",
      "Numpad . (period) frames the selected object.",
      "Alt+click selects edge/face loops in Edit Mode.",
      "Ctrl+click to draw a lasso select in Edit Mode.",
    ],
    commonMistakes: [
      "Transforming in the wrong space — check the Transform Orientation (top header) before moving.",
      "Accidentally leaving Edit Mode — Tab is easy to hit accidentally. Check the mode in the top-left dropdown.",
      "Using Global instead of Local for object-aligned transforms.",
    ],
    relatedEditors: ["properties", "outliner", "shader-editor"],
    screenshotPlaceholder: "Blender 3D Viewport in Solid mode showing a character mesh in Edit Mode. Toolbar on left with modeling tools, N-Panel open on right showing Item location. Mode selector at top showing 'Edit Mode'. Viewport overlays active showing wireframe overlay",
    tags: ["viewport", "3d", "model", "edit", "sculpt", "object", "main"],
  },

  {
    id: "properties",
    name: "Properties",
    shortName: "Properties",
    icon: "⚙️",
    color: "orange",
    description: "Side panel containing all settings for the active object, scene, render, and physics.",
    purpose: "Central hub for configuring every aspect of objects, materials, modifiers, constraints, physics, and render settings.",
    whatYouCanDo: [
      "Assign and configure modifiers",
      "Set up physics simulations",
      "Create and assign materials",
      "Configure object constraints",
      "Set render engine and output settings",
      "Manage particle systems",
      "Configure scene-wide lighting and world settings",
    ],
    keyAreas: [
      { name: "Render Properties", location: "Camera icon tab", description: "Render engine (EEVEE/Cycles), sampling, output resolution, file format." },
      { name: "Output Properties", location: "Printer icon tab", description: "Output path, frame range, resolution, file format." },
      { name: "Scene Properties", location: "Scene icon tab", description: "Scene units, gravity, audio settings." },
      { name: "Object Properties", location: "Orange square tab", description: "Object visibility, display, transform locks, relations." },
      { name: "Modifier Properties", location: "Wrench icon tab", description: "Add and configure all modifiers for the active object." },
      { name: "Material Properties", location: "Sphere icon tab", description: "Material slots, material creation." },
      { name: "Physics Properties", location: "Particles/physics tab", description: "Cloth, rigid body, soft body, fluid simulations." },
      { name: "Object Data Properties", location: "Mesh/curve/etc icon", description: "Mesh vertex groups, shape keys, UV maps, normals." },
    ],
    beginnerExplanation: "The Properties panel is where you change what your objects DO and LOOK LIKE. It has icons down the left side for different categories. The wrench is for modifiers, the sphere is for materials.",
    advancedExplanation: "Properties panels are context-sensitive — they show data for the active object. When multiple objects are selected, only the active (brightest outline) object's properties show. Drivers and expressions can be entered into any numerical field (Ctrl+D or type # before a value).",
    commonWorkflows: [
      "Wrench tab → Add Modifier → select modifier type",
      "Sphere tab → New → set material name → go to Shader Editor",
      "Camera tab → set render engine → adjust samples",
      "Particles tab → Add particle system",
    ],
    shortcuts: [
      { key: "Ctrl+P", action: "Set parent (Object Mode)" },
      { key: "Alt+P", action: "Clear parent" },
      { key: "Ctrl+D", action: "Add driver to property field" },
    ],
    tips: [
      "Right-click any property field to add it to the Quick Favorites bar.",
      "Hover over any property to see its Python path — useful for drivers and scripting.",
      "Multiple objects can be batch-edited if you use Ctrl+L to copy properties.",
    ],
    commonMistakes: [
      "Looking for modifier settings on the wrong object — check the header shows the correct active object.",
      "Changing material on a linked object — you need to Make Single User first (Object menu).",
    ],
    relatedEditors: ["3d-viewport", "shader-editor", "outliner"],
    screenshotPlaceholder: "Blender Properties panel showing the Modifier Properties tab (wrench icon) with Subdivision Surface and Bevel modifiers stacked. Tab icons visible on the left. Context header shows active object name",
    tags: ["properties", "modifiers", "materials", "settings", "physics", "render", "configure"],
  },

  {
    id: "outliner",
    name: "Outliner",
    shortName: "Outliner",
    icon: "🌲",
    color: "green",
    description: "Scene hierarchy view showing all objects, collections, and data blocks.",
    purpose: "Navigate and organize the scene hierarchy, manage visibility, and link/unlink data.",
    whatYouCanDo: [
      "See all objects in the scene",
      "Organize objects into Collections",
      "Toggle object visibility (eye icon)",
      "Toggle render visibility (camera icon)",
      "Manage parenting hierarchy",
      "Search for objects by name",
      "Lock objects to prevent accidental selection",
    ],
    keyAreas: [
      { name: "Display Mode", location: "Top header dropdown", description: "Scenes, View Layer, Data Blocks, Libraries, Orphan Data modes." },
      { name: "Filter", location: "Funnel icon", description: "Filter by object type, selected, or custom." },
      { name: "Hierarchy tree", location: "Main area", description: "Nested tree showing Collections and their objects with parenting." },
      { name: "Visibility icons", location: "Right side of each row", description: "Eye=viewport, Camera=render, Selection=selectable, Instance=hide in outliner." },
    ],
    beginnerExplanation: "The Outliner is like a file explorer for your scene. Every object appears here. Click to select, drag to reparent, and use the eye icon to hide things.",
    advancedExplanation: "Collections in the Outliner map to render layers and view layers. Linked libraries appear in a separate color. Data Block mode (BLENDER_FILE) shows everything in the .blend including unused materials and textures for cleanup. Use Orphan Data view to purge unused assets.",
    commonWorkflows: [
      "Drag object onto a Collection to move it",
      "M key to move selected to a different Collection",
      "Click the Eye icon to toggle visibility per object",
      "Type in the search bar at top to filter by name",
    ],
    shortcuts: [
      { key: "A", action: "Select All in Outliner" },
      { key: "M", action: "Move selected to Collection (with popup)" },
      { key: "F2", action: "Rename selected item" },
    ],
    tips: [
      "Use Collections to organize complex scenes — characters, props, lights, FX each in their own collection.",
      "Ctrl+click a visibility icon to toggle ALL children of a collection.",
      "Select an object in viewport → it highlights in Outliner (enabled by default).",
    ],
    commonMistakes: [
      "Deleting Collections removes all objects inside — use Right-click → Unlink instead to just remove the collection wrapper.",
      "Confusing viewport hide (Eye) with render hide (Camera) — objects can be visible in viewport but excluded from render.",
    ],
    relatedEditors: ["3d-viewport", "properties"],
    screenshotPlaceholder: "Blender Outliner panel showing a scene with Collections: Character (containing body, hair, eyes), Props, Lights, Cameras. Some objects have eye icon disabled (hidden). Hierarchy shows parenting with indentation",
    tags: ["outliner", "hierarchy", "collection", "organize", "visibility", "scene", "tree"],
  },

  {
    id: "shader-editor",
    name: "Shader Editor",
    shortName: "Shader Editor",
    icon: "🎨",
    color: "purple",
    description: "Node-based material editor for creating and connecting shader nodes.",
    purpose: "Build complex materials from composable nodes — textures, mixing, color grading, procedural patterns.",
    whatYouCanDo: [
      "Create node-based materials",
      "Mix multiple textures and shaders",
      "Create procedural patterns without image textures",
      "Set up emission, transparency, subsurface scattering",
      "Create metallic, glass, and skin materials",
      "Wire textures to displacement for geometry detail",
    ],
    keyAreas: [
      { name: "Header", location: "Top", description: "Switch between Object/World/Line Style materials. Add node menu. View controls." },
      { name: "Node Graph", location: "Main area", description: "Connect and arrange shader nodes. Material Output on the right." },
      { name: "Sidebar (N)", location: "Right panel", description: "Node settings, texture coordinates info." },
    ],
    beginnerExplanation: "Instead of sliders for your material, you connect node boxes with wires. Each node does one thing (like 'make noise' or 'mix two colors'). Connect them up and you get a material.",
    advancedExplanation: "The Principled BSDF handles most PBR workflows with a single node. For advanced rendering: connect multiple BSDFs with Mix Shader by a Factor (like a mask). Node Groups encapsulate sub-networks for reuse. OSL (Open Shading Language) nodes available in Cycles CPU mode.",
    commonWorkflows: [
      "Add Image Texture → connect to Principled BSDF Base Color",
      "Add Noise Texture → Color Ramp → Bump → Normal of Principled",
      "Shift+D to duplicate nodes, Ctrl+X to delete and reconnect",
      "Ctrl+Shift+click to preview any node's output",
    ],
    shortcuts: [
      { key: "Shift+A", action: "Add Node menu" },
      { key: "Ctrl+Shift+Click", action: "Preview node output" },
      { key: "M", action: "Mute/unmute node" },
      { key: "Ctrl+G", action: "Group selected nodes into Node Group" },
      { key: "Tab", action: "Enter/exit Node Group" },
    ],
    tips: [
      "Use Node Wrangler add-on — Ctrl+T to add texture setup automatically, Ctrl+Shift+click to preview.",
      "Principled BSDF handles 95% of real-world materials — learn it deeply first.",
      "Color Ramp is the most versatile utility node — use it to remap any gradient.",
    ],
    commonMistakes: [
      "Connecting a non-color texture to Color input without switching Image Texture to 'Non-Color' — gamma-encodes the data incorrectly.",
      "Plugging Roughness into Base Color socket — check socket types (yellow=color, grey=float).",
    ],
    relatedEditors: ["3d-viewport", "texture-node-editor"],
    screenshotPlaceholder: "Blender Shader Editor showing a PBR material setup. Principled BSDF in center. Image Texture nodes for Color, Roughness, Normal connected. ColorRamp remapping noise for surface variation. Material Output on far right",
    tags: ["shader", "material", "nodes", "pbr", "texture", "principled", "cycles"],
  },

  {
    id: "geometry-node-editor",
    name: "Geometry Node Editor",
    shortName: "Geo Nodes",
    icon: "🔷",
    color: "blue",
    description: "Node-based procedural geometry editor for non-destructive mesh operations.",
    purpose: "Create procedural geometry, scatter objects, modify meshes, simulate motion, and build parametric assets — all without destructive modeling.",
    whatYouCanDo: [
      "Scatter instances across surfaces",
      "Procedurally generate geometry from math",
      "Modify and filter mesh attributes",
      "Animate geometry procedurally",
      "Create modular/parametric assets",
      "Run simulation zones for physics-like effects",
    ],
    keyAreas: [
      { name: "Node Graph", location: "Main area", description: "Connect geometry nodes. Input on left, Group Output on right." },
      { name: "Group Input", location: "Left node", description: "Exposes parameters to the Properties panel for artist control." },
      { name: "Spreadsheet", location: "Separate editor type", description: "View attribute values per vertex/edge/face." },
    ],
    beginnerExplanation: "Connect geometry nodes to procedurally modify or generate 3D shapes without touching the original mesh. The Group Output is where the final geometry comes out.",
    advancedExplanation: "Geometry Nodes uses a field system — attributes flow through the tree as fields, evaluated lazily per element. Simulation Zones (4.0+) allow stateful simulation within the node tree. Named attributes persist between frames and can be baked.",
    commonWorkflows: [
      "Distribute Points on Faces → Instance on Points → scatter trees/rocks",
      "Mesh to Points → Instance on Points for grid scattering",
      "Capture Attribute → store computed values for reuse",
      "Simulation Zone for snowfall accumulation, aging effects",
    ],
    shortcuts: [
      { key: "Shift+A", action: "Add node" },
      { key: "Ctrl+G", action: "Create Node Group" },
      { key: "Tab", action: "Enter Node Group" },
      { key: "Ctrl+Shift+Click", action: "Preview node geometry in viewport" },
    ],
    tips: [
      "The Spreadsheet editor is your debugger — it shows exact attribute values per geometry element.",
      "Named Attributes are the 'variables' of Geometry Nodes — store custom data with Store Named Attribute.",
      "Expose any value as a Group Input to make parametric assets with slider controls in Properties.",
    ],
    commonMistakes: [
      "Modifying geometry in Edit Mode after adding Geometry Nodes — GN runs after Edit Mode so changes interact unexpectedly.",
      "Forgetting Realize Instances before certain operations — instanced geometry is virtual until Realized.",
    ],
    relatedEditors: ["3d-viewport", "properties", "spreadsheet"],
    screenshotPlaceholder: "Blender Geometry Node Editor showing a tree scattering setup: Mesh Domain of terrain feeding into Distribute Points on Faces → Instance on Points using a tree collection → Group Output. 3D viewport on left showing forest result",
    tags: ["geometry nodes", "procedural", "scatter", "instances", "modifier", "attributes", "parametric"],
  },

  {
    id: "uv-editor",
    name: "UV Editor",
    shortName: "UV Editor",
    icon: "📐",
    color: "yellow",
    description: "2D view for editing UV map coordinates that control how textures wrap onto meshes.",
    purpose: "Lay out UV islands so textures map correctly and efficiently onto 3D geometry.",
    whatYouCanDo: [
      "Unwrap UV coordinates",
      "Move, rotate, scale UV islands",
      "Pack UVs efficiently",
      "Pin and stitch UV seams",
      "Load reference images for UV alignment",
      "Check texture stretching with Stretch overlay",
    ],
    keyAreas: [
      { name: "UV Islands", location: "Main area", description: "The 2D layout of UV coordinates. Each island is a flattened mesh section." },
      { name: "Image selector", location: "Top header", description: "Load a texture to see behind your UVs for alignment." },
      { name: "UV menu", location: "Top header", description: "Unwrap, Pack Islands, Seams, Stitch, Weld, Snap tools." },
    ],
    beginnerExplanation: "Think of UV editing as unfolding a cardboard box flat — you cut along seams and unfold the 3D mesh into 2D so a texture can be painted on it.",
    advancedExplanation: "UV space is 0–1 in both U and V. Tiles (UDIMs) extend the UV space to 1001+ for high-res texture atlases. Smart UV Project is fast for hard-surface. Follow Active Quads works for clean quad meshes. Lightmap Pack maximizes texel density for baked lighting.",
    commonWorkflows: [
      "Mark seams in Edit Mode (Ctrl+E → Mark Seam) → U → Unwrap",
      "A to select all UVs → UV menu → Pack Islands",
      "Use Stretch overlay to identify distorted UVs (red = stretched)",
      "P to pin selected UVs before running Pack",
    ],
    shortcuts: [
      { key: "U", action: "Unwrap menu (in Edit Mode / UV Editor)" },
      { key: "P (in UV Editor)", action: "Pin selected UVs" },
      { key: "Alt+P", action: "Unpin UVs" },
      { key: "Ctrl+E", action: "Edge menu (Mark/Clear Seam in Edit Mode)" },
      { key: "V", action: "Stitch selected UV islands" },
    ],
    tips: [
      "Mark seams along natural feature lines — back of ears, underarms, between sole and upper of a shoe.",
      "Use Smart UV Project for hard-surface/mechanical objects — often good enough without manual seams.",
      "Overlapping UVs are fine when mirrored objects share a single UV space (character arms, legs).",
    ],
    commonMistakes: [
      "Not marking seams before unwrapping — Blender guesses wrong seam locations.",
      "Ignoring UV stretching (red in Stretch overlay) — textures look distorted in render.",
    ],
    relatedEditors: ["3d-viewport", "image-editor"],
    screenshotPlaceholder: "Blender UV Editor showing a character head unwrapped into islands. Stretch overlay active showing mostly green (no stretch) with some yellow at chin. Mark Seam visible behind ear. Image texture loaded as background",
    tags: ["uv", "unwrap", "texture", "seam", "islands", "map", "layout"],
  },

  {
    id: "image-editor",
    name: "Image Editor",
    shortName: "Image Editor",
    icon: "🖼️",
    color: "yellow",
    description: "View and paint 2D images, including rendered output and texture painting canvas.",
    purpose: "Display rendered frames, view textures, and perform basic 2D image editing and texture painting.",
    whatYouCanDo: [
      "View and zoom into render results",
      "Compare render passes",
      "Texture paint in 2D",
      "View/edit image sequences",
      "Save rendered images",
      "Apply basic color corrections",
    ],
    keyAreas: [
      { name: "Image selector", location: "Top header", description: "Switch between open images, render result, or viewer nodes." },
      { name: "Toolbar", location: "Left side (Texture Paint mode)", description: "Brush tools for 2D texture painting." },
      { name: "Header overlay icons", location: "Top right", description: "Channels (RGBA), zoom level." },
    ],
    beginnerExplanation: "Where your renders appear when you press F12. Also used to view and paint textures.",
    advancedExplanation: "In Texture Paint mode, the Image Editor and 3D Viewport work together — paint in 2D or 3D simultaneously. Render result stores the last render. Use Compositor nodes with Viewer node to preview compositing in real-time.",
    commonWorkflows: [
      "F12 to render → result appears in Image Editor",
      "Alt+S to save the render result",
      "Switch to Texture Paint mode to paint directly on the texture",
    ],
    shortcuts: [
      { key: "F12", action: "Render and view in Image Editor" },
      { key: "Alt+S", action: "Save image" },
      { key: "S (in Texture Paint)", action: "Sample color" },
    ],
    tips: [
      "Split the Image Editor and 3D Viewport for simultaneous texture painting.",
      "Image Editor can preview any Compositor Viewer node output in real-time.",
    ],
    commonMistakes: ["Closing the render result without saving — F12 overwrites the previous render result."],
    relatedEditors: ["uv-editor", "compositor"],
    screenshotPlaceholder: "Blender Image Editor showing a completed Cycles render of a character. Header shows image selector on Render Result. Bottom shows image info (3840×2160, RGB, 32-bit). View is zoomed into the face detail",
    tags: ["image", "render", "texture", "paint", "view", "2d", "output"],
  },

  {
    id: "compositor",
    name: "Compositor",
    shortName: "Compositor",
    icon: "🖥️",
    color: "green",
    description: "Node-based post-processing editor for combining render layers and applying effects.",
    purpose: "Composite render passes, apply color grading, glare, blur, and combine multiple renders into a final image.",
    whatYouCanDo: [
      "Color grade renders",
      "Add glow/bloom (Glare node)",
      "Depth of field compositing",
      "Motion blur post-processing",
      "Combine multiple render layers",
      "Add lens distortion and chromatic aberration",
      "Add vignette effects",
    ],
    keyAreas: [
      { name: "Render Layers node", location: "Left input", description: "Receives render passes (Color, Depth, Normal, etc.) from the renderer." },
      { name: "Composite node", location: "Right output", description: "Final output that overwrites the render result." },
      { name: "Viewer node", location: "Optional preview", description: "Preview any node's output in the Image Editor." },
    ],
    beginnerExplanation: "After rendering, Compositor lets you apply effects like color correction, bloom, and depth of field — non-destructively, without re-rendering.",
    advancedExplanation: "Multi-layer EXR output from render → load as Image node → composite separate elements (beauty, shadows, reflections) with mathematical control. Use View Transform (Filmic/AgX) before Composite node for consistent color. GPU compositing available in Blender 4.2+.",
    commonWorkflows: [
      "Render Layer → Color Balance → Glare → Composite",
      "RGB Curves for quick color grade",
      "Lens Distortion node for cinematic barrel distortion",
    ],
    shortcuts: [
      { key: "Shift+A", action: "Add compositor node" },
      { key: "Ctrl+Shift+Click", action: "Route to Viewer node to preview" },
    ],
    tips: [
      "Render with EXR multi-layer output — composite in post without re-rendering.",
      "Use the Viewer node to preview any point in the compositing tree.",
      "Backdrop (Alt+click) shows the current node's result as a background in the compositor.",
    ],
    commonMistakes: [
      "Not enabling 'Use Nodes' in the header — compositor doesn't activate until this is on.",
      "Compositing changes not appearing in F12 render — compositor runs after rendering finishes.",
    ],
    relatedEditors: ["image-editor", "3d-viewport"],
    screenshotPlaceholder: "Blender Compositor showing a film post-processing network. Render Layers → Glare (Fog Glow) → Color Balance → Lens Distortion → Composite. Viewer node on Glare output showing bloom effect preview",
    tags: ["compositor", "color grade", "glare", "post-process", "render", "vfx", "bloom"],
  },

  {
    id: "dope-sheet",
    name: "Dope Sheet",
    shortName: "Dope Sheet",
    icon: "📋",
    color: "orange",
    description: "Displays keyframes as dots on a timeline, for timing and spacing of animation.",
    purpose: "Visualize and edit keyframe timing across all animated properties simultaneously.",
    whatYouCanDo: [
      "See all keyframes for all objects/properties at once",
      "Move and scale keyframes in time",
      "Copy/paste keyframes between objects",
      "Filter by object or data type",
      "Set keyframe interpolation type",
      "Work with Action clips",
    ],
    keyAreas: [
      { name: "Timeline channel", location: "Left list", description: "Shows object/bone/property names with expandable sub-channels." },
      { name: "Keyframe grid", location: "Main area", description: "Diamonds/dots representing keyframes on a time axis." },
      { name: "Action editor mode", location: "Header dropdown", description: "Switch to Action mode to work with NLA-compatible Action blocks." },
    ],
    beginnerExplanation: "Shows all your keyframes as dots on a timeline. Drag them left/right to change timing. Scale them (S) to speed up or slow down animation.",
    advancedExplanation: "Dope Sheet shows Actions linked to objects. Right-click keyframes to change interpolation (Bezier/Linear/Constant). Select channels then use T to change interpolation for all. Use the Action Editor mode to create named Actions for NLA. Markers (M) label specific frames.",
    commonWorkflows: [
      "A to select all keyframes → S to scale timing",
      "G to move keyframes in time",
      "Right-click → Interpolation Mode to change easing",
      "Channel filtering to show only specific properties",
    ],
    shortcuts: [
      { key: "I", action: "Insert Keyframe at current frame" },
      { key: "Alt+I", action: "Delete Keyframe" },
      { key: "T", action: "Set Interpolation Mode" },
      { key: "V", action: "Set Handle Type (Bezier handles)" },
      { key: "G/S", action: "Grab/Scale selected keyframes" },
    ],
    tips: [
      "Box select keyframes then scale (S) to compress/expand timing without changing poses.",
      "Press Home to frame all keyframes in view.",
    ],
    commonMistakes: [
      "Moving keyframes when wrong context is active — click in the Dope Sheet first.",
      "Deleting keyframes instead of blocking them — right-click the channel and mute it instead.",
    ],
    relatedEditors: ["graph-editor", "timeline", "nla-editor"],
    screenshotPlaceholder: "Blender Dope Sheet showing a character walk cycle with keyframes across bones. Left: bone channel list expanded showing hip, spine, arm bones. Right: diamond keyframes at frames 1, 8, 16, 24 forming the cycle",
    tags: ["dope sheet", "keyframe", "timing", "animation", "action", "pose"],
  },

  {
    id: "graph-editor",
    name: "Graph Editor",
    shortName: "Graph Editor",
    icon: "📈",
    color: "green",
    description: "Edits animation curves (F-Curves) to control interpolation between keyframes.",
    purpose: "Fine-tune the exact speed, easing, and feel of every animated parameter using Bezier curves.",
    whatYouCanDo: [
      "Adjust easing in and out of keyframes",
      "Create bounces, elastic effects, overshoots",
      "Control curve extrapolation (what happens before/after keyframes)",
      "Loop curves using Modifiers (Cycles modifier)",
      "Manually edit curve values for precision",
    ],
    keyAreas: [
      { name: "F-Curve", location: "Main area", description: "Bezier curve showing value over time. Control points are keyframes, handles control easing." },
      { name: "Channel list", location: "Left", description: "Lists all animated properties with their curves." },
      { name: "Curve Modifiers", location: "N-Panel → Modifiers", description: "Non-destructive curve effects like Cycles, Noise, Envelope." },
    ],
    beginnerExplanation: "The curve shows how a value (like position) changes over time. A flat curve = no movement. A steep slope = fast movement. Drag the handles to control acceleration.",
    advancedExplanation: "Handle types: Auto (smooth), Vector (linear), Free (fully manual). Extrapolation Constant/Linear/Cyclic (for looping). Add a Cycles modifier to the curve for infinite loop from just 2 keyframes. Noise modifier adds procedural jitter.",
    commonWorkflows: [
      "Select a keyframe → V → choose Vector handles for linear movement",
      "N-Panel → Modifiers → Add Cycles for looping animation",
      "Ctrl+click on curve to add a new control point",
    ],
    shortcuts: [
      { key: "V", action: "Set handle type (Auto/Vector/Free/Aligned)" },
      { key: "T", action: "Set interpolation type" },
      { key: "N", action: "Open N-Panel for curve modifiers and values" },
    ],
    tips: [
      "The Cycles modifier is the easiest way to create looping animations from non-looping curves.",
      "Hold Alt while dragging a handle to adjust both sides symmetrically.",
    ],
    commonMistakes: [
      "Auto handles losing curve shape when keyframes are added nearby — switch to Free handles for precision.",
      "Curve extrapolation defaulting to Constant — set to Cyclic for loop animations.",
    ],
    relatedEditors: ["dope-sheet", "timeline"],
    screenshotPlaceholder: "Blender Graph Editor showing a bouncing ball animation curve. Location Z property shown as S-curve with sharp landing at bottom and slow arc at top. Handle types visible as yellow dots with control arms",
    tags: ["f-curve", "animation", "easing", "interpolation", "graph", "bezier", "timing"],
  },

  {
    id: "timeline",
    name: "Timeline",
    shortName: "Timeline",
    icon: "⏱️",
    color: "yellow",
    description: "Simple time strip showing current frame and playback controls.",
    purpose: "Control frame playback, set start/end frame, add simple keyframes.",
    whatYouCanDo: [
      "Play, pause, and scrub animation",
      "Set start and end frame",
      "Jump to keyframes",
      "Insert keyframes (I)",
      "Set frame rate",
    ],
    keyAreas: [
      { name: "Frame input", location: "Top left", description: "Current frame number. Drag or type to change." },
      { name: "Playback controls", location: "Center", description: "Play, stop, step forward/back, jump to start/end." },
      { name: "Start/End frame", location: "Top right", description: "Animation range." },
    ],
    beginnerExplanation: "The bottom strip with play/pause. Press Spacebar to play your animation. Drag the blue line to scrub to any frame.",
    advancedExplanation: "Frame rate set here affects all editors. Sync modes (None/Frame Drop/V-Sync) control playback smoothness. Preview range (P key) sets a sub-range for faster playback testing.",
    commonWorkflows: ["Spacebar to play", "Shift+Left/Right to jump between keyframes", "P to set preview range"],
    shortcuts: [
      { key: "Space", action: "Play / Pause" },
      { key: "Left/Right arrow", action: "Step one frame" },
      { key: "Shift+Left/Right", action: "Jump to previous/next keyframe" },
      { key: "Home", action: "Jump to start frame" },
      { key: "End", action: "Jump to end frame" },
      { key: "P", action: "Set preview range" },
    ],
    tips: ["Shift+Spacebar in Viewport to play without needing the Timeline focused."],
    commonMistakes: ["Forgetting to extend the frame range — animation clips at the end frame."],
    relatedEditors: ["dope-sheet", "graph-editor"],
    screenshotPlaceholder: "Blender Timeline at the bottom of the screen showing frames 1–250. Blue scrubber at frame 42. Start frame=1, End frame=250 shown. Playback controls in center. Keyframe markers visible on the strip",
    tags: ["timeline", "playback", "frame", "animation", "time", "scrub"],
  },

  {
    id: "nla-editor",
    name: "NLA Editor",
    shortName: "NLA Editor",
    icon: "🎬",
    color: "purple",
    description: "Non-Linear Animation editor for mixing, layering, and blending animation clips.",
    purpose: "Combine multiple Actions into a final animation — reusing walk cycles, layering expressions on a walk, or mixing motion capture clips.",
    whatYouCanDo: [
      "Stack NLA strips (Actions) on multiple tracks",
      "Blend between animations by overlapping strips",
      "Scale strips to change animation speed",
      "Combine motion capture with hand-keyed animation",
      "Reuse walk/run/idle cycles",
    ],
    keyAreas: [
      { name: "Tracks", location: "Horizontal strips", description: "Each object can have multiple NLA tracks stacked vertically." },
      { name: "NLA Strips", location: "Colored rectangles on tracks", description: "Each strip represents an Action at a position in time." },
      { name: "Star/Push Down button", location: "Track header", description: "Pushes the active Action into the NLA as a strip, freeing the Action for re-editing." },
    ],
    beginnerExplanation: "Lets you combine separate animations (a walk cycle + a wave + an idle) by laying them out as clips on tracks — like a video editing timeline but for animations.",
    advancedExplanation: "Use Add Influence (Blend Type) to layer animations additively. Scale strips to change speed. Repeat a strip (Strip properties → Repeat) to loop a cycle. Mute strips with H. Connect strip endings with curves for blending.",
    commonWorkflows: [
      "Create Action → NLA Editor → Push Down → creates NLA strip",
      "Shift+A to add a new strip from existing Actions",
      "S to scale strip duration (changes animation speed)",
    ],
    shortcuts: [
      { key: "N", action: "Strip properties panel" },
      { key: "Shift+A", action: "Add NLA strip from existing Actions" },
      { key: "S", action: "Scale selected strip" },
      { key: "Tab", action: "Edit strip in place (tweak mode)" },
    ],
    tips: ["Use Repeat in strip properties to loop a walk cycle for as many steps as needed without duplicating keyframes."],
    commonMistakes: ["Forgetting to Push Down an Action before adding a new one — the old Action gets orphaned."],
    relatedEditors: ["dope-sheet", "graph-editor"],
    screenshotPlaceholder: "Blender NLA Editor showing a character with 3 tracks: Walk Cycle (strip spanning frames 1–80 repeated 4 times), Wave Arm (additive strip at frames 40–60), Idle Pose (strip at frames 0–1 as base). Colored strips on each track",
    tags: ["nla", "animation", "clip", "track", "mix", "action", "blend"],
  },

  {
    id: "spreadsheet",
    name: "Spreadsheet",
    shortName: "Spreadsheet",
    icon: "📊",
    color: "green",
    description: "Displays attribute values for every geometry element — the debugger for Geometry Nodes.",
    purpose: "Inspect, debug, and understand attribute values on vertices, edges, faces, and instances.",
    whatYouCanDo: [
      "View all attribute values per vertex/edge/face",
      "Debug Geometry Nodes attribute flow",
      "See position, normal, UV, and custom attribute values",
      "Inspect instance transforms",
      "Filter by domain and data type",
    ],
    keyAreas: [
      { name: "Domain selector", location: "Top header", description: "Point (vertex), Edge, Face, Face Corner, or Instance." },
      { name: "Filter toggle", location: "Top header", description: "Show only selected elements." },
      { name: "Attribute columns", location: "Main table", description: "Each column is one attribute; each row is one geometry element." },
    ],
    beginnerExplanation: "Shows you every number behind your mesh — like a table of all your vertices with their positions, colors, and custom values. Mostly useful when working with Geometry Nodes.",
    advancedExplanation: "Evaluates the full Geometry Nodes modifier stack up to the pinned node. Use Ctrl+click on a node in the Geo Node editor to pin the Spreadsheet to that node's output for step-by-step debugging.",
    commonWorkflows: [
      "Work with Geometry Nodes → Spreadsheet in split view to debug attribute values",
      "Ctrl+click a node in Geo Node editor to pin Spreadsheet to that output",
    ],
    shortcuts: [{ key: "Ctrl+click (node in GN editor)", action: "Pin Spreadsheet to that node's geometry output" }],
    tips: ["The Spreadsheet is the only way to verify attribute names are spelled correctly and contain the right data type."],
    commonMistakes: ["Spreadsheet showing wrong data — check which node is pinned and which domain is selected."],
    relatedEditors: ["geometry-node-editor"],
    screenshotPlaceholder: "Blender Spreadsheet editor showing vertex attribute table. Columns: Position (X,Y,Z), Normal (X,Y,Z), custom attribute 'density' (float). 2547 rows (vertices). Domain selector shows 'Point'. Filter showing only selected verts",
    tags: ["spreadsheet", "attributes", "geometry nodes", "debug", "data", "vertex", "inspect"],
  },

  {
    id: "text-editor",
    name: "Text Editor",
    shortName: "Text Editor",
    icon: "📝",
    color: "yellow",
    description: "Write and run Python scripts directly inside Blender.",
    purpose: "Scripting, automation, creating add-ons, and running Python commands against the Blender API.",
    whatYouCanDo: [
      "Write Python scripts",
      "Run scripts with Alt+P",
      "Browse the bpy API",
      "Create and test add-ons",
      "Batch-process scenes with Python",
      "Automate repetitive tasks",
    ],
    keyAreas: [
      { name: "Text block selector", location: "Top header", description: "Open, create, or load .py files." },
      { name: "Editor area", location: "Main", description: "Syntax-highlighted Python code editor." },
      { name: "Run Script button", location: "Top header", description: "Executes the current script." },
    ],
    beginnerExplanation: "A code editor built into Blender where you can write Python scripts. Press Alt+P or click Run Script to execute your code.",
    advancedExplanation: "Access any Blender function via the bpy module. The Python Console shows the exact Python equivalent of any action. Scripts have access to bpy.context.scene, bpy.data, and bpy.ops for full Blender control. Use bpy.app.timers for event-loop deferred execution.",
    commonWorkflows: [
      "import bpy → write script → Alt+P to run",
      "bpy.ops.object.select_all(action='DESELECT') to deselect all",
      "Copy Python path from Properties tooltip → use in script",
    ],
    shortcuts: [
      { key: "Alt+P", action: "Run current script" },
      { key: "Ctrl+Space", action: "Autocomplete (basic)" },
    ],
    tips: ["Right-click any property in the interface and 'Copy Full Data Path' to get its Python API path."],
    commonMistakes: ["Running scripts that crash Blender — save your .blend file first."],
    relatedEditors: ["python-console"],
    screenshotPlaceholder: "Blender Text Editor showing a Python script that renames all selected objects with a prefix. Syntax highlighting shows keywords in blue, strings in green. Run Script button highlighted in header. Output in Info log at bottom",
    tags: ["python", "script", "code", "automation", "api", "bpy", "addon"],
  },

  {
    id: "python-console",
    name: "Python Console",
    shortName: "Python Console",
    icon: "🐍",
    color: "green",
    description: "Interactive Python shell with autocomplete for the Blender API.",
    purpose: "Quick Python commands, API exploration, and interactive testing without writing full scripts.",
    whatYouCanDo: [
      "Run single Python commands",
      "Explore the bpy API with autocomplete (Tab)",
      "Test script snippets interactively",
      "Access and modify scene data live",
    ],
    keyAreas: [
      { name: "Input line", location: "Bottom", description: "Type Python commands here and press Enter." },
      { name: "Output history", location: "Main area", description: "Shows results of each command." },
    ],
    beginnerExplanation: "Like a Python terminal but connected to Blender — type bpy.context.scene.name and press Enter to see your scene's name.",
    advancedExplanation: "Tab autocomplete traverses the bpy module tree. Use it for API discovery. The console has access to the same context as scripts. History scrollable with Up/Down arrows.",
    commonWorkflows: [
      "Type bpy. then Tab to see all available modules",
      "bpy.context.selected_objects to list selected",
    ],
    shortcuts: [{ key: "Tab", action: "Autocomplete" }, { key: "Up/Down", action: "Command history" }],
    tips: ["Use the Python Console to discover the exact bpy path of any property before scripting."],
    commonMistakes: ["Trying to run multi-line scripts — use the Text Editor for scripts with more than one line."],
    relatedEditors: ["text-editor"],
    screenshotPlaceholder: "Blender Python Console showing interactive session. User typed 'bpy.context.object.name' and got result 'Cube'. Tab autocomplete showing bpy.context.object options list. Green prompt at bottom",
    tags: ["python", "console", "interactive", "bpy", "api", "shell", "autocomplete"],
  },

];

// ─── Indexes ─────────────────────────────────────────────────────────────────

export const EDITOR_INDEX: EditorIndex[] = BLENDER_EDITORS.map(e => ({
  id: e.id,
  name: e.name,
  icon: e.icon,
  color: e.color,
  description: e.description,
  tags: e.tags,
}));

export const EDITOR_MAP: Record<string, BlenderEditor> = Object.fromEntries(
  BLENDER_EDITORS.map(e => [e.id, e])
);
