import type { BlenderNode } from "./types";

export const BLENDER_NODES: BlenderNode[] = [

  // ── GEOMETRY NODES ──────────────────────────────────────────────────────

  {
    id: "join-geometry",
    name: "Join Geometry",
    category: "geometry-nodes",
    subcategory: "Geometry",
    icon: "🔗",
    color: "blue",
    description: "Combines multiple geometry streams into a single output.",
    whyItExists: "Geometry Nodes splits operations into separate branches. Join Geometry merges those branches back into one object before the output.",
    whenToUse: "Whenever you have two or more geometry streams (e.g. scatter + base mesh) that need to be combined before the Group Output.",
    inputs: [
      { name: "Geometry", type: "Geometry", description: "First geometry input (multi-input — connect as many as you need)", default: "None" },
    ],
    outputs: [
      { name: "Geometry", type: "Geometry", description: "All input geometries merged into one" },
    ],
    beginnerExplanation: "Think of it like glue. If you have a rock and some grass made separately, Join Geometry sticks them together so they act as one object.",
    advancedExplanation: "Join Geometry is a multi-input node — drag multiple connections to its single socket. It preserves all attributes, materials, and instance data from each input stream. Order matters for overlapping attributes: later inputs overwrite earlier ones when names conflict.",
    commonUseCases: [
      "Merging a scattered object field with the base terrain mesh",
      "Combining multiple procedural elements (grass + rocks + trees) before output",
      "Attaching generated geometry (e.g. extruded edges) back to the original mesh",
    ],
    typicalConnections: [
      "Instance on Points → Join Geometry",
      "Transform Geometry → Join Geometry",
      "Set Material → Join Geometry",
    ],
    exampleWorkflow: "Scatter rocks on a terrain: Terrain Mesh → Set Material. Distribute Points on Faces → Instance on Points (Rocks) → Join Geometry. Connect both branches to Join Geometry → Group Output.",
    commonMistakes: [
      "Forgetting to join streams before Group Output — only one geometry can reach the output",
      "Not realizing Join Geometry preserves instances — use Realize Instances first if you need editable mesh",
      "Connecting wrong sockets — Join Geometry only accepts Geometry type",
    ],
    performanceTips: [
      "Join late in the node tree — operate on separate streams as long as possible",
      "If performance is critical, minimize the number of materials across joined meshes",
    ],
    relatedNodes: ["realize-instances", "separate-geometry", "delete-geometry"],
    frequentlyUsedWith: ["instance-on-points", "set-material", "transform-geometry"],
    screenshotPlaceholder: "Blender Geometry Nodes editor showing Join Geometry node with three inputs connected: a terrain mesh, scattered rocks via Instance on Points, and grass blades. The node is highlighted in blue with multiple lines feeding into it.",
    quiz: [
      { question: "What type of socket does Join Geometry accept?", answer: "Geometry (multi-input)" },
      { question: "What happens when two inputs have the same named attribute?", answer: "The later input's attribute overwrites the earlier one" },
    ],
    practiceExercise: "Create a simple scatter system: add a Plane, enter Geometry Nodes. Add a Cube as an object to instance. Use Distribute Points on Faces → Instance on Points → Join Geometry (with the original plane) → Group Output. You should see the plane with cubes scattered on it.",
    blenderVersion: "3.0+",
    tags: ["join","merge","combine","geometry","multi-input","output"],
  },

  {
    id: "instance-on-points",
    name: "Instance on Points",
    category: "geometry-nodes",
    subcategory: "Instances",
    icon: "✨",
    color: "purple",
    description: "Places instances of an object or collection at each point in a point cloud.",
    whyItExists: "Manually duplicating objects is not procedural. Instance on Points lets you place thousands of objects at exact positions, rotations, and scales driven by fields — with zero manual work.",
    whenToUse: "Any time you want to scatter objects: trees on terrain, rocks in a scene, bolts on a surface, flowers in a field.",
    inputs: [
      { name: "Points", type: "Geometry", description: "Point cloud or mesh to place instances at" },
      { name: "Selection", type: "Boolean", description: "Which points get an instance" },
      { name: "Instance", type: "Geometry", description: "The object or collection to instance" },
      { name: "Pick Instance", type: "Boolean", description: "Pick randomly from a collection" },
      { name: "Instance Index", type: "Integer", description: "Which collection item to use" },
      { name: "Rotation", type: "Rotation", description: "Rotation of each instance" },
      { name: "Scale", type: "Vector", description: "Scale of each instance" },
    ],
    outputs: [
      { name: "Instances", type: "Geometry", description: "Geometry with instances placed at each point" },
    ],
    beginnerExplanation: "Imagine stamping a tree shape at every dot on a dotted canvas. Instance on Points does exactly that — it takes your dots (points) and stamps a copy of any object at each one.",
    advancedExplanation: "Instances are not real geometry until Realize Instances is used — they are lightweight references. Use Random Value or Noise Texture nodes to vary rotation and scale per instance. The Pick Instance toggle lets you randomly assign objects from a Collection.",
    commonUseCases: [
      "Scattering trees, rocks, or grass across terrain",
      "Placing rivets, bolts, or details along a surface",
      "Creating crowds or repeated architectural elements",
      "Building procedural forests with random variation",
    ],
    typicalConnections: [
      "Distribute Points on Faces → Instance on Points (Points)",
      "Object Info → Instance on Points (Instance)",
      "Random Value → Instance on Points (Rotation/Scale)",
    ],
    exampleWorkflow: "Add terrain mesh → Geometry Nodes → Distribute Points on Faces (connects to Points) → Instance on Points. Set Instance to an Object Info node pointing to your tree object. Connect Random Value (0–360°) to Rotation Z for variation.",
    commonMistakes: [
      "Connecting a Mesh to Instance instead of an Object Info node",
      "Forgetting that instances aren't real geometry — Boolean operations won't work until Realize Instances is applied",
      "Not using Join Geometry to combine instances with the base mesh before output",
    ],
    performanceTips: [
      "Keep instances as instances — don't use Realize Instances unless absolutely necessary",
      "Use a lower density Distribute Points on Faces with viewport subdivision for preview",
      "Limit scale variation to avoid very large or very small instances that hurt visual quality",
    ],
    relatedNodes: ["distribute-points-on-faces", "realize-instances", "join-geometry"],
    frequentlyUsedWith: ["distribute-points-on-faces", "object-info", "random-value"],
    screenshotPlaceholder: "Geometry Nodes editor with Instance on Points node. Left side shows a Distribute Points on Faces node feeding into Points socket. An Object Info node feeding into Instance socket. The 3D viewport shows hundreds of small tree objects scattered across a terrain.",
    quiz: [
      { question: "What node do you use to get a Geometry input from a scene object?", answer: "Object Info" },
      { question: "What does 'Pick Instance' do?", answer: "Randomly picks an object from a collection to place at each point" },
    ],
    practiceExercise: "Create a scatter system: Add a UV Sphere, name it 'Rock'. Add a Plane and add Geometry Nodes to it. Inside the node tree: Distribute Points on Faces → Instance on Points. Add Object Info referencing 'Rock' and connect to Instance. Add Random Value (Vector) to Scale. Watch the viewport fill with spheres.",
    blenderVersion: "3.0+",
    tags: ["instance","scatter","points","procedural","distribution","duplicate"],
  },

  {
    id: "distribute-points-on-faces",
    name: "Distribute Points on Faces",
    category: "geometry-nodes",
    subcategory: "Point",
    icon: "📍",
    color: "green",
    description: "Generates a point cloud distributed across the faces of a mesh.",
    whyItExists: "To create scatter systems without hand-placing every point. Drives Instance on Points for procedural scattering.",
    whenToUse: "When you want random or Poisson-disk distributed points on any mesh surface — the foundation of most scatter workflows.",
    inputs: [
      { name: "Mesh", type: "Geometry", description: "The mesh to distribute points on" },
      { name: "Selection", type: "Boolean", description: "Limit distribution to selected faces" },
      { name: "Distance Min", type: "Float", description: "Minimum distance between points (Poisson Disk only)" },
      { name: "Density Max", type: "Float", description: "Maximum point density (Poisson Disk only)" },
      { name: "Density", type: "Float", description: "Points per unit² (Random mode)" },
      { name: "Density Factor", type: "Float", description: "Multiplier — use texture to vary density" },
      { name: "Seed", type: "Integer", description: "Random seed for reproducible results" },
    ],
    outputs: [
      { name: "Points", type: "Geometry", description: "A point cloud on the mesh surface" },
      { name: "Normal", type: "Vector", description: "Face normal at each point" },
      { name: "Rotation", type: "Rotation", description: "Rotation aligned to face normal" },
    ],
    beginnerExplanation: "It creates dots on the surface of a mesh — like randomly sprinkling seeds on a field. Then other nodes can put objects at each dot.",
    advancedExplanation: "Two modes: Random (fast, uniform density) and Poisson Disk (respects minimum distance, more natural-looking). Connect a Noise Texture to Density Factor to create dense/sparse variation across the surface. The Normal output gives you face normals for aligning instances.",
    commonUseCases: [
      "Scattering grass, rocks, trees on terrain",
      "Creating hair/fur distribution systems",
      "Distributing detail elements (rivets, stones) on surfaces",
      "Building procedural ecosystems",
    ],
    typicalConnections: [
      "Group Input (Mesh) → Distribute Points on Faces",
      "Distribute Points on Faces (Points) → Instance on Points",
      "Noise Texture → Distribute Points on Faces (Density Factor)",
    ],
    exampleWorkflow: "Terrain → Distribute Points on Faces. Set Density to 5. Connect a Noise Texture (mapped to position) to Density Factor so forests cluster naturally. Feed Points into Instance on Points for tree placement.",
    commonMistakes: [
      "Using Random mode and wondering why objects overlap — switch to Poisson Disk for natural spacing",
      "Forgetting to connect the Normal output to Instance on Points Rotation for surface-aligned instances",
      "Setting density too high and crashing the viewport",
    ],
    performanceTips: [
      "Start with Density = 1 and increase gradually",
      "Use Poisson Disk's Distance Min to prevent overlap without computing too many points",
      "Mask with a weight-painted vertex group via Selection input for art-directed scatter",
    ],
    relatedNodes: ["instance-on-points", "points-to-vertices", "set-position"],
    frequentlyUsedWith: ["instance-on-points", "noise-texture-gn", "random-value"],
    screenshotPlaceholder: "Geometry Nodes editor showing Distribute Points on Faces node. Mode dropdown set to 'Poisson Disk'. A Noise Texture feeds into Density Factor. The 3D viewport shows a terrain with point cloud dots visible as orange dots spread naturally across the surface.",
    quiz: [
      { question: "Which mode prevents points from overlapping?", answer: "Poisson Disk" },
      { question: "What output gives you the surface normal direction at each point?", answer: "Normal" },
    ],
    practiceExercise: "Add a Plane. Scale it up 10x. Add Geometry Nodes. Place Distribute Points on Faces between Group Input and Group Output. Set Density to 10. Switch to Poisson Disk mode. Add a Noise Texture to Density Factor. Watch the point distribution change on the surface.",
    blenderVersion: "3.0+",
    tags: ["distribute","points","scatter","faces","density","poisson","random"],
  },

  {
    id: "set-position",
    name: "Set Position",
    category: "geometry-nodes",
    subcategory: "Geometry",
    icon: "📌",
    color: "yellow",
    description: "Moves geometry points by setting or offsetting their position.",
    whyItExists: "To procedurally move vertices, points, or control points using math, textures, or field expressions — the foundation of procedural deformation.",
    whenToUse: "Any time you want to displace, wave, ripple, noise-deform, or animate geometry positions procedurally.",
    inputs: [
      { name: "Geometry", type: "Geometry", description: "The geometry to modify" },
      { name: "Selection", type: "Boolean", description: "Which points are affected" },
      { name: "Position", type: "Vector", description: "New absolute position (if used)" },
      { name: "Offset", type: "Vector", description: "Amount to move each point from its current position" },
    ],
    outputs: [
      { name: "Geometry", type: "Geometry", description: "Geometry with updated positions" },
    ],
    beginnerExplanation: "It moves points. You can tell each point exactly where to go (Position) or tell it how far to move from where it already is (Offset). Use a noise texture as the offset to create a bumpy, wavy, or organic deformation.",
    advancedExplanation: "The Offset input is usually more useful than Position. Feed a Noise Texture → Vector Math (to scale it) into Offset for displacement effects. Combine with the Position field to create position-based deformation that varies across the mesh. Works on all geometry types including curves and point clouds.",
    commonUseCases: [
      "Displacing a grid with noise to create terrain",
      "Creating wave animations by driving offset with time",
      "Bending or deforming curves procedurally",
      "Offsetting instances based on index",
    ],
    typicalConnections: [
      "Noise Texture → Vector Math → Set Position (Offset)",
      "Position (field) → Math → Set Position (Offset)",
      "Set Position → Group Output",
    ],
    exampleWorkflow: "Add a Grid mesh (100x100 subdivisions). In Geometry Nodes: Group Input → Set Position. Add Noise Texture, plug into Offset. Scale the noise output with Vector Math (Multiply by 0,0,1 to only move on Z). Result: procedural terrain from a flat grid.",
    commonMistakes: [
      "Using Position instead of Offset and snapping all points to the same position",
      "Not scaling the noise output — default noise is too subtle or too extreme",
      "Forgetting to multiply by a Z-only vector when you only want vertical displacement",
    ],
    performanceTips: [
      "For terrain, use a lower-resolution grid and rely on a Subdivision Surface modifier",
      "Bake the displacement to an actual mesh when the geometry is finalized",
    ],
    relatedNodes: ["noise-texture-gn", "vector-math", "position-field"],
    frequentlyUsedWith: ["noise-texture-gn", "math-node", "combine-xyz"],
    screenshotPlaceholder: "Geometry Nodes editor with Set Position node. A Noise Texture feeds into a Vector Math Multiply node (with 0,0,1 to isolate Z), which connects to the Offset socket. The 3D viewport shows a flat grid deformed into rolling terrain.",
    quiz: [
      { question: "What is the difference between Position and Offset inputs?", answer: "Position sets an absolute location; Offset moves points relative to where they already are" },
      { question: "How do you only move points on the Z axis?", answer: "Multiply the offset vector by (0, 0, 1) using Vector Math" },
    ],
    practiceExercise: "Create terrain: Add Grid (100x100 verts). Add Geometry Nodes. Wire Group Input → Set Position → Group Output. Add Noise Texture, connect to Offset. Use Vector Math to multiply by (0,0,2). You have procedural terrain.",
    blenderVersion: "3.0+",
    tags: ["position","offset","deform","displace","move","transform","noise","terrain"],
  },

  {
    id: "transform-geometry",
    name: "Transform Geometry",
    category: "geometry-nodes",
    subcategory: "Geometry",
    icon: "↔️",
    color: "yellow",
    description: "Applies translation, rotation, and scale to an entire geometry.",
    whyItExists: "To move, rotate, or scale geometry as a whole inside a node tree without affecting the object's origin or transforms.",
    whenToUse: "When you need to offset or rotate a geometry branch before joining it with another, or when adjusting an instanced object's transform.",
    inputs: [
      { name: "Geometry", type: "Geometry", description: "Input geometry" },
      { name: "Translation", type: "Vector", description: "XYZ offset" },
      { name: "Rotation", type: "Rotation", description: "XYZ rotation in radians" },
      { name: "Scale", type: "Vector", description: "XYZ scale" },
    ],
    outputs: [
      { name: "Geometry", type: "Geometry", description: "Transformed geometry" },
    ],
    beginnerExplanation: "It moves, rotates, or scales your whole geometry — like pressing G, R, S in the viewport but inside a node tree.",
    advancedExplanation: "Transform Geometry operates in the object's local space. Unlike Set Position (which works per-point), Transform moves the entire geometry at once. Useful for adjusting the orientation of geometry before instancing or before joining streams.",
    commonUseCases: [
      "Centering geometry to the origin before instancing",
      "Rotating a curve path or profile for Curve to Mesh",
      "Adjusting imported/linked geometry that has an offset origin",
    ],
    typicalConnections: ["Group Input → Transform Geometry → Join Geometry"],
    exampleWorkflow: "If a linked asset has its origin offset, use Transform Geometry with a negative Translation to center it before feeding it into Instance on Points.",
    commonMistakes: [
      "Confusing this with Set Position — Transform moves all points uniformly; Set Position can move each point differently",
    ],
    performanceTips: ["Has minimal overhead — use freely"],
    relatedNodes: ["set-position", "join-geometry", "object-info"],
    frequentlyUsedWith: ["join-geometry", "instance-on-points"],
    screenshotPlaceholder: "Transform Geometry node in Geometry Nodes editor. Translation, Rotation, and Scale inputs visible with numeric values. A mesh is visibly offset from the origin in the viewport.",
    quiz: [{ question: "What is the difference between Transform Geometry and Set Position?", answer: "Transform Geometry moves all points uniformly as one object; Set Position can move each point independently using fields" }],
    practiceExercise: "Add a Cube, apply Geometry Nodes. Use Transform Geometry to offset it by (2,0,0) inside the node tree. Notice the cube moves but the origin stays at center.",
    blenderVersion: "3.0+",
    tags: ["transform","move","rotate","scale","translate","geometry"],
  },

  {
    id: "realize-instances",
    name: "Realize Instances",
    category: "geometry-nodes",
    subcategory: "Instances",
    icon: "📐",
    color: "red",
    description: "Converts instanced geometry into actual editable mesh geometry.",
    whyItExists: "Instances are lightweight references — they can't be modified per-element by most nodes. Realize Instances converts them to real geometry so further operations work correctly.",
    whenToUse: "When you need to apply further geometry operations (Boolean, Merge by Distance, attribute transfer) to instanced geometry.",
    inputs: [
      { name: "Geometry", type: "Geometry", description: "Geometry containing instances" },
      { name: "Selection", type: "Boolean", description: "Which instances to realize" },
      { name: "Realize All", type: "Boolean", description: "Realize nested instances too" },
    ],
    outputs: [
      { name: "Geometry", type: "Geometry", description: "Realized mesh geometry" },
    ],
    beginnerExplanation: "Instances are like shortcuts — fast but limited. Realize Instances turns those shortcuts into real geometry, so you can do more things to them. Warning: this can be very slow with thousands of instances.",
    advancedExplanation: "After Realize Instances, every instance becomes actual mesh data. Attributes get baked into the realized geometry. Performance can drop significantly — avoid using this until the end of your node tree, and only when necessary.",
    commonUseCases: ["Applying a Merge by Distance after scattering", "Boolean operations on scattered geometry", "Exporting instance geometry as a single mesh"],
    typicalConnections: ["Instance on Points → Realize Instances → Merge by Distance"],
    exampleWorkflow: "Scatter rocks → Instance on Points → Realize Instances → Merge by Distance (to weld touching geometry) → Group Output.",
    commonMistakes: ["Using Realize Instances too early and destroying performance", "Applying it to thousands of instances when only a Boolean is needed"],
    performanceTips: ["Place as late as possible in the tree", "Only realize what you actually need to modify"],
    relatedNodes: ["instance-on-points", "join-geometry", "merge-by-distance"],
    frequentlyUsedWith: ["instance-on-points", "merge-by-distance"],
    screenshotPlaceholder: "Realize Instances node connected after Instance on Points. The viewport shows the same scattered objects but now selected as actual mesh geometry (orange highlights on individual polygons) instead of as instances.",
    quiz: [{ question: "Why should you avoid using Realize Instances early in a node tree?", answer: "It converts lightweight instances to real geometry, which can be extremely slow with many instances" }],
    practiceExercise: "Create a scatter system with 100 instances. Check viewport performance. Then add Realize Instances after. Notice the frame rate difference.",
    blenderVersion: "3.0+",
    tags: ["realize","instances","convert","mesh","geometry","performance"],
  },

  {
    id: "merge-by-distance",
    name: "Merge by Distance",
    category: "geometry-nodes",
    subcategory: "Geometry",
    icon: "🔀",
    color: "green",
    description: "Merges vertices that are within a set distance of each other.",
    whyItExists: "Procedural geometry often creates duplicate or nearly-coincident vertices. Merge by Distance cleans these up automatically.",
    whenToUse: "After Realize Instances, after Curve to Mesh, or whenever you need to weld nearby vertices for a watertight mesh.",
    inputs: [
      { name: "Geometry", type: "Geometry", description: "Input mesh" },
      { name: "Selection", type: "Boolean", description: "Which vertices can be merged" },
      { name: "Distance", type: "Float", description: "Maximum merge distance", default: "0.001" },
    ],
    outputs: [{ name: "Geometry", type: "Geometry", description: "Mesh with merged vertices" }],
    beginnerExplanation: "If two points are very close together, this node sticks them into one point. Like clicking 'Remove Doubles' in old Blender — it cleans up tiny gaps.",
    advancedExplanation: "Equivalent to Edit Mode's Merge by Distance (formerly Remove Doubles). The Distance value is in scene units. Too large a value will collapse geometry you want to keep; too small will miss floating vertices.",
    commonUseCases: ["Cleaning up Curve to Mesh seams", "Welding realized instances that should be connected", "Removing duplicate vertices from imported data"],
    typicalConnections: ["Realize Instances → Merge by Distance → Group Output"],
    exampleWorkflow: "Curve to Mesh (closed curve) → Merge by Distance (Distance 0.001) to close any seam gap at the curve's start/end point.",
    commonMistakes: ["Setting Distance too high and merging geometry that should stay separate", "Forgetting to Realize Instances first — works on mesh, not instances"],
    performanceTips: ["Only apply when needed — it recalculates topology which has a cost"],
    relatedNodes: ["realize-instances", "delete-geometry", "join-geometry"],
    frequentlyUsedWith: ["realize-instances", "curve-to-mesh"],
    screenshotPlaceholder: "Merge by Distance node with Distance set to 0.001m. Before/after viewport comparison showing seam gap at curve junction closed after the node.",
    quiz: [{ question: "What is the equivalent operation in Edit Mode?", answer: "Merge by Distance (formerly 'Remove Doubles')" }],
    practiceExercise: "Create a Grid. In Geometry Nodes, add Merge by Distance. Set Distance to 1m. Watch vertices collapse. Reduce to 0.001m to see the correct behavior.",
    blenderVersion: "3.0+",
    tags: ["merge","distance","weld","clean","vertices","remove doubles"],
  },

  {
    id: "curve-to-mesh",
    name: "Curve to Mesh",
    category: "geometry-nodes",
    subcategory: "Curve",
    icon: "〰️",
    color: "blue",
    description: "Converts a curve into a mesh by extruding it along a profile curve.",
    whyItExists: "Curves define paths and shapes mathematically. Curve to Mesh converts them into renderable, editable mesh geometry with a cross-section profile.",
    whenToUse: "Building roads, pipes, cables, rails, fences — any object that follows a path and has a cross-section shape.",
    inputs: [
      { name: "Curve", type: "Geometry", description: "The path curve (the spine)" },
      { name: "Profile Curve", type: "Geometry", description: "The cross-section shape" },
      { name: "Fill Caps", type: "Boolean", description: "Cap the ends of the mesh" },
    ],
    outputs: [{ name: "Mesh", type: "Geometry", description: "The resulting mesh" }],
    beginnerExplanation: "Draw a path (like a road center line). Draw a cross-section shape (like a rectangle for the road width). Curve to Mesh slides the cross-section along the path to create the 3D road.",
    advancedExplanation: "The Profile Curve defines the shape of the cross-section. A Circle profile gives you a pipe; a Rectangle profile gives you a rail or road. Use Spline Parameter to drive material variation along the length. Fill Caps adds geometry to close the ends.",
    commonUseCases: ["Roads and paths on terrain", "Pipes and cables", "Architectural moldings and rails", "Procedural fences"],
    typicalConnections: ["Curve Line / Bezier Curve → Curve to Mesh (Curve)", "Curve Circle / Quadrilateral → Curve to Mesh (Profile Curve)"],
    exampleWorkflow: "Add Bezier Curve to scene. In Geometry Nodes on another object: Object Info (Bezier) → Curve to Mesh. Object Info (Circle profile) → Curve to Mesh Profile. Enable Fill Caps. Result: a tube following the bezier path.",
    commonMistakes: ["Forgetting to add a Profile Curve — without it, the output is flat", "Using Fill Caps with an open (non-cyclic) profile — causes unexpected capping"],
    performanceTips: ["Keep the profile curve simple (4-8 verts for pipes)", "Reduce curve resolution for distant objects"],
    relatedNodes: ["fill-curve", "curve-to-points", "set-curve-radius"],
    frequentlyUsedWith: ["curve-line", "merge-by-distance", "set-material"],
    screenshotPlaceholder: "Curve to Mesh node. Left: an S-curve path from Object Info. Below: a Circle profile from Object Info. Result in viewport: a smooth tube following the S-curve path with capped ends.",
    quiz: [{ question: "What does the Profile Curve input define?", answer: "The cross-section shape of the mesh along the path" }],
    practiceExercise: "Add a Bezier Curve. Add an empty object with Geometry Nodes. Use Object Info to reference the curve → Curve to Mesh. Add a Curve Circle as the profile. You should get a tube.",
    blenderVersion: "3.0+",
    tags: ["curve","mesh","convert","pipe","road","path","extrude","profile"],
  },

  {
    id: "set-material",
    name: "Set Material",
    category: "geometry-nodes",
    subcategory: "Material",
    icon: "🎨",
    color: "purple",
    description: "Assigns a material to geometry within a node tree.",
    whyItExists: "To apply or change materials procedurally, including applying different materials to different parts of the geometry based on field conditions.",
    whenToUse: "Whenever you need to assign a material inside a Geometry Nodes tree rather than through the material slot on the object.",
    inputs: [
      { name: "Geometry", type: "Geometry", description: "Geometry to assign material to" },
      { name: "Selection", type: "Boolean", description: "Which faces get the material" },
      { name: "Material", type: "Material", description: "The material to assign" },
    ],
    outputs: [{ name: "Geometry", type: "Geometry", description: "Geometry with material assigned" }],
    beginnerExplanation: "It paints a material onto your geometry. You pick a material from your .blend file and this node applies it to the mesh — without leaving the node tree.",
    advancedExplanation: "Set Material works on faces. Combined with a Selection field (e.g. Compare or Index), you can assign different materials to different parts of the same geometry — creating procedural multi-material workflows.",
    commonUseCases: ["Applying a road material to a Curve to Mesh road", "Setting materials on scattered instances", "Multi-material procedural objects"],
    typicalConnections: ["Curve to Mesh → Set Material → Group Output", "Join Geometry → Set Material → Group Output"],
    exampleWorkflow: "Road system: Curve to Mesh → Set Material (Road Asphalt material) → Group Output.",
    commonMistakes: ["Forgetting to link an actual material in the node dropdown", "Using Set Material on instances before Realize Instances — it won't apply to the instance geometry"],
    performanceTips: ["Minimize material count across a node tree for better draw call performance"],
    relatedNodes: ["join-geometry", "realize-instances"],
    frequentlyUsedWith: ["curve-to-mesh", "join-geometry"],
    screenshotPlaceholder: "Set Material node in Geometry Nodes. Material picker dropdown showing 'Road_Asphalt' selected. The 3D viewport shows the road mesh rendered with a grey asphalt material.",
    quiz: [{ question: "Can Set Material apply different materials to different faces?", answer: "Yes, by using a Boolean field in the Selection input" }],
    practiceExercise: "Create a grid. Add Geometry Nodes. Place Set Material between Group Input and Output. Create two materials. Use an Index > 50 Boolean to assign material 2 to half the faces.",
    blenderVersion: "3.0+",
    tags: ["material","assign","shader","procedural","faces"],
  },

  {
    id: "noise-texture-gn",
    name: "Noise Texture",
    category: "geometry-nodes",
    subcategory: "Texture",
    icon: "🌊",
    color: "blue",
    description: "Generates multi-frequency Perlin noise as a float or color value.",
    whyItExists: "Organic, natural-looking variation in nature follows noise patterns. This node provides procedural noise for displacement, density variation, color patterns, and more.",
    whenToUse: "For terrain generation, displacement, scatter density variation, procedural color patterns — any time you need organic random variation.",
    inputs: [
      { name: "Vector", type: "Vector", description: "Position input (use Position field for 3D noise)" },
      { name: "W", type: "Float", description: "4D noise coordinate (use for time-based animation)" },
      { name: "Scale", type: "Float", description: "Overall size of noise features", default: "5.0" },
      { name: "Detail", type: "Float", description: "Number of noise layers (octaves)", default: "2.0" },
      { name: "Roughness", type: "Float", description: "Roughness between octaves", default: "0.5" },
      { name: "Lacunarity", type: "Float", description: "Frequency multiplier per octave", default: "2.0" },
      { name: "Distortion", type: "Float", description: "Warps the noise coordinates", default: "0.0" },
    ],
    outputs: [
      { name: "Value", type: "Float", description: "Noise as 0–1 float" },
      { name: "Color", type: "Color", description: "Noise as grayscale color" },
    ],
    beginnerExplanation: "Creates a random blobby pattern — like clouds or hills. Plug it into the Offset of Set Position and your flat grid becomes a bumpy terrain. Plug it into Density and your scatter becomes denser in some areas.",
    advancedExplanation: "Perlin noise is computed from the Vector input (usually the Position field). Scale controls zoom. Detail adds finer layers of noise (higher = more complex but slower). Distortion warps the noise coordinate space for twisted patterns. Use the W input animated over time to create flowing/animated noise.",
    commonUseCases: ["Terrain height displacement", "Scatter density variation", "Procedural material patterns", "Animated flowing effects"],
    typicalConnections: ["Position → Noise Texture (Vector)", "Noise Texture (Value) → Set Position (Offset Z)"],
    exampleWorkflow: "Position field → Noise Texture (Scale=3, Detail=4) → Vector Math (Multiply by 0,0,2) → Set Position Offset. Creates terrain.",
    commonMistakes: ["Not connecting a Position field to Vector — without it, all points get the same noise value", "Setting Detail too high (above 8) — diminishing returns and performance cost", "Forgetting to isolate the Z axis when creating terrain"],
    performanceTips: ["Keep Detail below 6 for real-time use", "Cache/bake displacement when geometry is final"],
    relatedNodes: ["set-position", "vector-math", "distribute-points-on-faces"],
    frequentlyUsedWith: ["set-position", "distribute-points-on-faces", "position-field"],
    screenshotPlaceholder: "Noise Texture node with Scale=5, Detail=4, Roughness=0.5. Position field connected to Vector input. Value output feeds into Set Position Offset. Viewport shows a grid deformed into organic terrain hills.",
    quiz: [{ question: "What input makes the noise vary across 3D space?", answer: "Connect the Position field to the Vector input" }],
    practiceExercise: "Add a Grid (50x50). Geometry Nodes: Position → Noise Texture → Multiply (Vector Math, factor 0,0,1) → Set Position Offset. Adjust Scale between 1 and 10. Watch terrain change.",
    blenderVersion: "3.0+",
    tags: ["noise","texture","perlin","procedural","random","terrain","displacement"],
  },

  {
    id: "group-input",
    name: "Group Input",
    category: "geometry-nodes",
    subcategory: "Group",
    icon: "📥",
    color: "green",
    description: "Exposes sockets from the Geometry Nodes modifier as editable parameters.",
    whyItExists: "To make node trees reusable and controllable — expose values that can be adjusted in the modifier panel without entering the node tree.",
    whenToUse: "Always at the start of every Geometry Nodes tree. Also use to expose parameters (density, scale, seed) that artists need to adjust.",
    inputs: [],
    outputs: [
      { name: "Geometry", type: "Geometry", description: "The object's mesh, passed into the node tree" },
      { name: "(Custom)", type: "Float", description: "Any socket type you add becomes an editable parameter" },
    ],
    beginnerExplanation: "It's the door that lets your object's geometry enter the node tree. Without it, the node tree has no mesh to work with. You can also add extra doors for numbers, colors, and other settings.",
    advancedExplanation: "Every socket added to Group Input appears in the Modifier panel as an adjustable parameter. This enables modular, reusable node groups. Use meaningful names and appropriate types. Geometry inputs can be used to accept external geometry (e.g. a terrain mesh passed in).",
    commonUseCases: ["Starting every Geometry Nodes tree", "Exposing density, scale, and seed controls", "Creating reusable node groups with parameters"],
    typicalConnections: ["Group Input (Geometry) → first operation node"],
    exampleWorkflow: "Group Input → Distribute Points on Faces → Instance on Points → Join Geometry → Group Output. The Geometry socket carries the object's mesh through.",
    commonMistakes: ["Deleting Group Input and wondering why there's no mesh to work with", "Not naming exposed parameters — they show as generic 'Value' in the modifier"],
    performanceTips: ["Expose only parameters you'll actually adjust — too many clutters the modifier panel"],
    relatedNodes: ["group-output"],
    frequentlyUsedWith: ["group-output"],
    screenshotPlaceholder: "Group Input node on the left side of a Geometry Nodes editor. The Geometry output socket (green) connects to the first operation. Additional exposed sockets (Density: Float, Seed: Integer) are visible in the Modifier panel on the right.",
    quiz: [{ question: "Where do Group Input sockets appear outside the node tree?", answer: "In the Geometry Nodes modifier panel on the object's properties" }],
    practiceExercise: "Add a node to your tree that exposes a Float called 'Density'. In the modifier panel, adjust it. This is your first reusable parameter.",
    blenderVersion: "3.0+",
    tags: ["group","input","parameter","modifier","expose","control"],
  },

  {
    id: "group-output",
    name: "Group Output",
    category: "geometry-nodes",
    subcategory: "Group",
    icon: "📤",
    color: "green",
    description: "Sends the final geometry out of the node tree to be displayed on the object.",
    whyItExists: "Every node tree needs a terminal output. Group Output is where the final geometry exits the node tree and appears in the viewport.",
    whenToUse: "Always — it's the last node in every Geometry Nodes tree.",
    inputs: [
      { name: "Geometry", type: "Geometry", description: "Final geometry to display" },
    ],
    outputs: [],
    beginnerExplanation: "It's the exit door for your geometry. Everything you built in the node tree comes out here and shows up on your object in the viewport.",
    advancedExplanation: "Only one Geometry socket connects to Group Output. If you have multiple geometry streams, use Join Geometry first. Additional output sockets can expose geometry attributes or values for use in other node trees (advanced compositing workflows).",
    commonUseCases: ["Terminating every Geometry Nodes tree", "Outputting final combined geometry"],
    typicalConnections: ["Join Geometry → Group Output", "Set Material → Group Output"],
    exampleWorkflow: "...Set Material → Join Geometry → Group Output. The mesh appears on the object.",
    commonMistakes: ["Connecting multiple geometry outputs directly — only one connects; use Join Geometry for multiple streams", "Accidentally deleting it — the object disappears from the viewport"],
    performanceTips: ["What you connect here gets evaluated every frame — keep the tree efficient"],
    relatedNodes: ["group-input", "join-geometry"],
    frequentlyUsedWith: ["join-geometry", "set-material"],
    screenshotPlaceholder: "Group Output node on the far right of a Geometry Nodes editor. A single green Geometry socket on the left receives the final node connection. The object in the viewport shows the result.",
    quiz: [{ question: "What node do you use before Group Output when you have multiple geometry streams?", answer: "Join Geometry" }],
    practiceExercise: "Intentionally disconnect Group Output. Notice the object disappears in the viewport. Reconnect it.",
    blenderVersion: "3.0+",
    tags: ["group","output","result","terminal","end"],
  },

  // ── SHADER NODES ────────────────────────────────────────────────────────

  {
    id: "principled-bsdf",
    name: "Principled BSDF",
    category: "shader-nodes",
    subcategory: "Shader",
    icon: "💎",
    color: "purple",
    description: "A single physically-based shader that covers most real-world materials.",
    whyItExists: "Before Principled BSDF, creating realistic materials required combining many separate shaders. Principled BSDF combines Diffuse, Glossy, Refraction, Subsurface Scattering, Clearcoat, and more into one artist-friendly node.",
    whenToUse: "For almost every material — skin, wood, metal, fabric, plastic, glass, ceramic. It is the default shader for PBR (Physically Based Rendering).",
    inputs: [
      { name: "Base Color", type: "Color", description: "The main color of the surface", default: "0.8, 0.8, 0.8" },
      { name: "Metallic", type: "Float", description: "0=dielectric, 1=fully metallic", default: "0.0" },
      { name: "Roughness", type: "Float", description: "0=mirror smooth, 1=fully rough", default: "0.5" },
      { name: "IOR", type: "Float", description: "Index of refraction for transmission", default: "1.45" },
      { name: "Alpha", type: "Float", description: "Surface opacity", default: "1.0" },
      { name: "Normal", type: "Vector", description: "Normal map input" },
      { name: "Subsurface Weight", type: "Float", description: "Subsurface scattering amount (for skin)", default: "0.0" },
      { name: "Transmission Weight", type: "Float", description: "Glass/refraction amount", default: "0.0" },
      { name: "Emission Color", type: "Color", description: "Glow/emission color" },
      { name: "Emission Strength", type: "Float", description: "Brightness of emission", default: "0.0" },
    ],
    outputs: [{ name: "BSDF", type: "Shader", description: "The computed shader" }],
    beginnerExplanation: "It's a magic box that makes your object look like almost anything real — shiny metal, rough wood, glowing lights, glass. You tweak the sliders and it looks right.",
    advancedExplanation: "Principled BSDF implements the Disney PBR model. Metallic = 1 disables the diffuse component and makes reflections tinted by Base Color. Roughness drives microfacet distribution. For realistic glass, set Transmission Weight = 1 and Roughness = 0. Subsurface Scattering simulates light penetration into translucent materials like skin or wax.",
    commonUseCases: ["Wood: Base Color texture, Roughness texture, Normal map", "Metal: Base Color, Metallic=1, Roughness texture", "Glass: Transmission=1, Roughness=0, IOR=1.45", "Skin: Subsurface Weight=0.3, Base Color, Normal map"],
    typicalConnections: ["Image Texture → Principled BSDF (Base Color)", "Principled BSDF → Material Output"],
    exampleWorkflow: "Wood material: Image Texture (wood diffuse) → Base Color. Image Texture (wood roughness) → Roughness. Image Texture (normal) → Normal Map → Normal. Principled BSDF → Material Output.",
    commonMistakes: ["Setting Metallic to 0.5 — in reality, materials are either metal or not (0 or 1)", "Using Emission without disabling bloom — can overpower a scene", "Forgetting Roughness texture — flat roughness looks plastic"],
    performanceTips: ["In Eevee, Transmission is expensive — avoid for background objects", "Subsurface Scattering has a render time cost in Cycles — use sparingly"],
    relatedNodes: ["image-texture", "normal-map", "color-ramp", "material-output"],
    frequentlyUsedWith: ["image-texture", "normal-map", "color-ramp"],
    screenshotPlaceholder: "Principled BSDF node with Base Color connected to a wood texture, Roughness to a roughness map, Normal to a Normal Map node. The material preview sphere shows realistic wood grain with proper specular highlights.",
    quiz: [
      { question: "What value should Metallic be for a plastic material?", answer: "0 — plastic is a dielectric (non-metal)" },
      { question: "How do you make glass with Principled BSDF?", answer: "Set Transmission Weight to 1.0 and Roughness to 0.0" },
    ],
    practiceExercise: "Create a gold material: Metallic=1.0, Base Color=(255,210,0), Roughness=0.2. Create a rubber material: Metallic=0, Base Color=(20,20,20), Roughness=0.9. Compare them in Material Preview.",
    blenderVersion: "3.0+",
    tags: ["shader","pbr","material","bsdf","principled","realistic","metal","glass","skin"],
  },

  {
    id: "image-texture",
    name: "Image Texture",
    category: "shader-nodes",
    subcategory: "Texture",
    icon: "🗺️",
    color: "yellow",
    description: "Loads and samples an image file as a texture.",
    whyItExists: "To bring real-world photographic textures, baked texture maps, and generated texture images into the material system.",
    whenToUse: "Whenever you want to use a photograph, scanned texture, or baked map as Base Color, Roughness, Normal, Metallic, or any other material input.",
    inputs: [
      { name: "Vector", type: "Vector", description: "UV coordinate or texture coordinate for sampling", default: "UV" },
    ],
    outputs: [
      { name: "Color", type: "Color", description: "Sampled color at that UV position" },
      { name: "Alpha", type: "Float", description: "Alpha channel of the image" },
    ],
    beginnerExplanation: "It reads a picture file and wraps it around your 3D object like sticker paper. The picture tells Blender what color each part of the surface should be.",
    advancedExplanation: "Image Texture samples the image at the UV coordinate. Connect a Mapping node + Texture Coordinate node to control tiling, offset, and rotation. Set Color Space to 'Non-Color' for non-color data maps (Roughness, Normal, Metallic) to avoid gamma correction errors. Interpolation controls sharpness: Closest for pixel art, Linear or Cubic for photos.",
    commonUseCases: ["Base Color from a photograph", "Roughness map from a PBR texture set", "Normal map from a scanned surface", "Alpha mask for transparency cutouts"],
    typicalConnections: ["Texture Coordinate → Mapping → Image Texture", "Image Texture → Principled BSDF"],
    exampleWorkflow: "Texture Coordinate (UV) → Mapping (Scale 2,2,1 for tiling) → Image Texture (wall_brick_diffuse.jpg) → Principled BSDF Base Color.",
    commonMistakes: ["Leaving Normal/Roughness/Metallic maps in sRGB color space — they must be 'Non-Color'", "Forgetting to UV unwrap the object — texture appears stretched or wrong", "Not connecting a Mapping node — can't adjust tiling"],
    performanceTips: ["Use mipmaps (enabled by default) for distant objects", "Compress textures to 8-bit when alpha isn't needed", "Match texture resolution to the object's visual size in the render"],
    relatedNodes: ["texture-coordinate", "mapping", "normal-map", "principled-bsdf"],
    frequentlyUsedWith: ["texture-coordinate", "mapping", "principled-bsdf"],
    screenshotPlaceholder: "Image Texture node with a brick texture loaded. The image preview thumbnail visible in the node. A Texture Coordinate node feeds into Vector via a Mapping node. The 3D object in the viewport shows the brick texture correctly tiled.",
    quiz: [
      { question: "What Color Space should you set for a Normal map or Roughness map?", answer: "Non-Color" },
      { question: "What node do you use to control tiling and offset of an Image Texture?", answer: "Mapping node" },
    ],
    practiceExercise: "Download a free PBR texture set (diffuse, roughness, normal). Create a material. Connect all three textures to Principled BSDF. Remember to set roughness and normal maps to Non-Color.",
    blenderVersion: "2.79+",
    tags: ["image","texture","uv","photograph","map","diffuse","color"],
  },

  {
    id: "color-ramp",
    name: "Color Ramp",
    category: "shader-nodes",
    subcategory: "Color",
    icon: "🌈",
    color: "yellow",
    description: "Maps a float value to a color gradient, or remaps a 0–1 range.",
    whyItExists: "To convert noise, gradients, or any float value into specific colors or to remap value ranges with precision and visual control.",
    whenToUse: "When you need to convert a noise value to a specific color palette, create edge highlighting, remap dirt/wear patterns, or design any gradient-based effect.",
    inputs: [{ name: "Fac", type: "Float", description: "Input value (0–1) that determines where on the gradient to sample" }],
    outputs: [
      { name: "Color", type: "Color", description: "Sampled color from the gradient" },
      { name: "Alpha", type: "Float", description: "Alpha from the gradient" },
    ],
    beginnerExplanation: "Imagine a ruler painted with colors. You tell it a number from 0 to 1, and it gives you the color at that position on the ruler. Used to turn grey noise into colorful patterns.",
    advancedExplanation: "Color Ramp supports multiple interpolation modes: Linear (smooth), Ease (S-curve), B-Spline (smooth), Cardinal, Constant (hard steps). Use Constant mode to create distinct bands (like cell shading or 3-tone shading). Drag stops to compress/expand parts of the range for precise control.",
    commonUseCases: ["Noise → Color Ramp → color variation on terrain", "Wear and dirt effects (remap AO or curvature)", "Converting procedural masks to high-contrast black/white", "Custom color palettes for stylized materials"],
    typicalConnections: ["Noise Texture → Color Ramp → Base Color", "Ambient Occlusion → Color Ramp → Principled BSDF"],
    exampleWorkflow: "Noise Texture (Value output) → Color Ramp (add stops: brown, green, white for terrain layers) → Principled BSDF Base Color. Creates biome-like terrain coloring.",
    commonMistakes: ["Not realizing Color Ramp also outputs a Float (Alpha) that can drive other inputs", "Setting all stops to the same color and wondering why nothing changes", "Using wrong interpolation mode — Constant gives hard steps; Linear gives smooth blends"],
    performanceTips: ["Color Ramp is very cheap — use freely"],
    relatedNodes: ["noise-texture-gn", "principled-bsdf", "mix-shader"],
    frequentlyUsedWith: ["noise-texture", "principled-bsdf", "mix-color"],
    screenshotPlaceholder: "Color Ramp node with three color stops: dark brown at 0, medium green at 0.5, white at 0.9. A Noise Texture feeds into Fac. The material preview sphere shows brown/green/snow terrain-like coloring.",
    quiz: [
      { question: "What interpolation mode creates hard color bands (like cel shading)?", answer: "Constant" },
      { question: "What is the input type for Color Ramp?", answer: "Float (Fac) — a value from 0 to 1" },
    ],
    practiceExercise: "Add a Noise Texture → Color Ramp → Base Color chain. Add 4 color stops: dark blue, sandy yellow, green, white. You just created a stylized terrain material.",
    blenderVersion: "2.79+",
    tags: ["color","ramp","gradient","remap","noise","pattern","palette"],
  },

  {
    id: "mix-shader",
    name: "Mix Shader",
    category: "shader-nodes",
    subcategory: "Shader",
    icon: "🔀",
    color: "purple",
    description: "Blends two shader outputs using a factor.",
    whyItExists: "To combine multiple shading effects — layering a transparent shader over a diffuse one creates translucency, mixing emission with diffuse creates a glowing surface.",
    whenToUse: "Whenever you need to blend two different materials or shader effects: wet/dry layers, decals over base, glow effects, opacity blending.",
    inputs: [
      { name: "Fac", type: "Float", description: "0=first shader only, 1=second shader only", default: "0.5" },
      { name: "Shader", type: "Shader", description: "First shader" },
      { name: "Shader", type: "Shader", description: "Second shader" },
    ],
    outputs: [{ name: "Shader", type: "Shader", description: "Blended result" }],
    beginnerExplanation: "Mix Shader is like a crossfade between two materials. At 0 you see only the first one; at 1 you see only the second; at 0.5 you see half of each.",
    advancedExplanation: "Fac can be driven by a texture for spatially-varying blending — e.g. a paint texture to blend between painted and bare metal, or a noise texture to create variation. Chain multiple Mix Shaders for complex layered materials.",
    commonUseCases: ["Blending Transparent BSDF + Principled BSDF for opacity", "Layering a wet shader over a dry shader", "Mixing Emission over a material for glow effects", "Alpha cutout with an image texture driving Fac"],
    typicalConnections: ["Principled BSDF + Transparent BSDF → Mix Shader → Material Output"],
    exampleWorkflow: "Transparency: Transparent BSDF (Shader 1) + Principled BSDF (Shader 2) + Image Texture Alpha → Fac → Mix Shader → Material Output.",
    commonMistakes: ["Mixing two shaders without a texture on Fac — gets uniform blend everywhere", "Forgetting to set Blend Mode to Alpha in Material Settings when using transparency in Eevee"],
    performanceTips: ["Avoid chaining many Mix Shaders in Cycles — each adds ray bounce complexity"],
    relatedNodes: ["principled-bsdf", "transparent-bsdf", "emission"],
    frequentlyUsedWith: ["principled-bsdf", "transparent-bsdf", "image-texture"],
    screenshotPlaceholder: "Mix Shader node blending a Principled BSDF (wood) with a Transparent BSDF. An image texture's Alpha output drives the Fac input. The material preview shows the wood with a transparent cutout region.",
    quiz: [{ question: "What Fac value shows only the second shader?", answer: "1.0" }],
    practiceExercise: "Create a leaf material: Image Texture (leaf diffuse) → Principled BSDF Base Color. Image Texture (same image) Alpha → Mix Shader Fac. Transparent BSDF as Shader 1. Result: leaf shape with transparent background.",
    blenderVersion: "2.79+",
    tags: ["mix","blend","shader","combine","layer","transparency","opacity"],
  },

  {
    id: "normal-map",
    name: "Normal Map",
    category: "shader-nodes",
    subcategory: "Vector",
    icon: "🗺️",
    color: "blue",
    description: "Converts a normal map image (blue-purple texture) into surface normal vectors.",
    whyItExists: "Normal maps store surface detail directions as colors. This node decodes those colors into actual normal vectors that the lighting system can use to fake surface detail without extra geometry.",
    whenToUse: "Every time you use a normal map texture from a PBR texture set or bake.",
    inputs: [
      { name: "Strength", type: "Float", description: "Intensity of the normal effect", default: "1.0" },
      { name: "Color", type: "Color", description: "The normal map image (must be Non-Color)" },
    ],
    outputs: [{ name: "Normal", type: "Vector", description: "Decoded surface normal for lighting" }],
    beginnerExplanation: "A normal map is a blue-purple picture that tricks the light into thinking the surface has bumps and crevices. This node reads that picture and tells the light how to bounce.",
    advancedExplanation: "Normal Map decodes tangent-space normal maps (the standard blue-tinted type). Space must match the bake space. Strength above 1.0 exaggerates the effect; below 1.0 softens it. For object-space normals, use the Object Space option. Always set the Image Texture color space to Non-Color before connecting.",
    commonUseCases: ["Adding surface detail to low-poly meshes", "Brick mortar grooves without actual geometry", "Fabric weave patterns", "Skin pores"],
    typicalConnections: ["Image Texture (Non-Color) → Normal Map → Principled BSDF (Normal)"],
    exampleWorkflow: "Image Texture (brick_normal.jpg, Non-Color) → Normal Map (Strength=1.0) → Principled BSDF Normal.",
    commonMistakes: ["Forgetting to set the Image Texture to Non-Color — produces wrong colors", "Connecting Color output directly to Normal without this node — doesn't work", "Strength too high (>2) making the surface look spiky"],
    performanceTips: ["Normal maps add minimal render time — use freely"],
    relatedNodes: ["image-texture", "principled-bsdf", "bump"],
    frequentlyUsedWith: ["image-texture", "principled-bsdf"],
    screenshotPlaceholder: "Normal Map node between an Image Texture (showing blue-purple normal map preview) and the Principled BSDF Normal socket. Strength=1.0. The material preview shows a flat plane that appears to have deep brick grooves.",
    quiz: [{ question: "What Color Space must the normal map Image Texture be set to?", answer: "Non-Color" }],
    practiceExercise: "Download a free normal map. Connect it through a Normal Map node to Principled BSDF. Compare the surface with Strength 0 vs 1 vs 3.",
    blenderVersion: "2.79+",
    tags: ["normal","map","bump","detail","surface","tangent","lighting"],
  },

  {
    id: "texture-coordinate",
    name: "Texture Coordinate",
    category: "shader-nodes",
    subcategory: "Input",
    icon: "📍",
    color: "green",
    description: "Provides UV, object, world, and camera coordinate systems for texturing.",
    whyItExists: "Different textures need different coordinate systems. UV unwrap coordinates for photorealistic textures, Object space for procedural materials that follow the object, Generated for quick automatic mapping.",
    whenToUse: "Whenever you use Image Texture or any procedural texture node — always control where the texture maps to.",
    inputs: [{ name: "Object", type: "Object", description: "Reference object for Object coordinate output" }],
    outputs: [
      { name: "Generated", type: "Vector", description: "Automatic 0-1 mapping based on bounding box" },
      { name: "Normal", type: "Vector", description: "Surface normal direction" },
      { name: "UV", type: "Vector", description: "UV map coordinates" },
      { name: "Object", type: "Vector", description: "Object local space" },
      { name: "Camera", type: "Vector", description: "Camera space" },
      { name: "Window", type: "Vector", description: "Render window space" },
      { name: "Reflection", type: "Vector", description: "Reflection direction" },
    ],
    beginnerExplanation: "It decides HOW the texture wraps around your object. UV means 'use the UV unwrap'. Generated means 'figure it out automatically'. Object means 'follow the object's local space'.",
    advancedExplanation: "UV is most common for textured assets. Object space makes procedural textures not stretch when the object is scaled. Generated space is 0-1 within the bounding box, useful for quick gradients. Always pair with a Mapping node for tiling/offset control.",
    commonUseCases: ["UV for PBR texture sets", "Object space for seamless procedural materials", "Generated for quick gradient setups"],
    typicalConnections: ["Texture Coordinate (UV) → Mapping → Image Texture"],
    exampleWorkflow: "Texture Coordinate (UV) → Mapping (Scale 2,2,1) → Image Texture.",
    commonMistakes: ["Not UV unwrapping the mesh before using UV coordinates — textures appear distorted", "Using Generated for Image Textures — gets distorted on non-cubic objects"],
    performanceTips: ["Free node — use freely"],
    relatedNodes: ["mapping", "image-texture"],
    frequentlyUsedWith: ["mapping", "image-texture"],
    screenshotPlaceholder: "Texture Coordinate node showing all output sockets. UV output connects to a Mapping node. The 3D viewport shows a UV-unwrapped mesh with a checker texture correctly mapped.",
    quiz: [{ question: "Which output should you use for a PBR texture set on a UV-unwrapped mesh?", answer: "UV" }],
    practiceExercise: "Apply a checker texture using Generated coordinates. Then UV unwrap the mesh and switch to UV coordinates. Notice the difference in how the texture maps.",
    blenderVersion: "2.79+",
    tags: ["texture","coordinate","uv","mapping","space","procedural"],
  },

  {
    id: "mapping",
    name: "Mapping",
    category: "shader-nodes",
    subcategory: "Vector",
    icon: "🗺️",
    color: "blue",
    description: "Controls the location, rotation, and scale of texture coordinates.",
    whyItExists: "Without Mapping, you can't tile, offset, or rotate a texture. It transforms the texture coordinate space before it reaches the texture node.",
    whenToUse: "Almost always — place between Texture Coordinate and every Image Texture or procedural texture to control tiling and positioning.",
    inputs: [
      { name: "Vector", type: "Vector", description: "Input texture coordinates" },
      { name: "Location", type: "Vector", description: "Offset the texture position" },
      { name: "Rotation", type: "Vector", description: "Rotate the texture" },
      { name: "Scale", type: "Vector", description: "Scale/tile the texture" },
    ],
    outputs: [{ name: "Vector", type: "Vector", description: "Transformed texture coordinates" }],
    beginnerExplanation: "It lets you zoom in, slide around, or rotate your texture. Scale=2,2,1 tiles the texture twice in X and Y. Location shifts it left or right.",
    advancedExplanation: "Scale values above 1 tile the texture (repeat more). Scale 0.5 makes the texture cover twice the area. Rotation in radians. Animate Location over time to create scrolling textures (for rivers, conveyor belts, lava). Node Wrangler addon adds quick Mapping + Texture Coordinate with Ctrl+T.",
    commonUseCases: ["Tiling textures on large surfaces", "Rotating textures to fix alignment", "Animating scrolling water or lava", "Offsetting patterns for variation"],
    typicalConnections: ["Texture Coordinate → Mapping → Image Texture"],
    exampleWorkflow: "Texture Coordinate (UV) → Mapping (Scale 4,4,1) → Image Texture (tile 4x in both directions).",
    commonMistakes: ["Setting Scale to 0 — texture disappears", "Confusing Location with Scale — Location shifts, Scale tiles"],
    performanceTips: ["Free — use freely"],
    relatedNodes: ["texture-coordinate", "image-texture"],
    frequentlyUsedWith: ["texture-coordinate", "image-texture"],
    screenshotPlaceholder: "Mapping node with Scale set to (4,4,1). Connected between Texture Coordinate UV output and Image Texture Vector input. The 3D floor plane shows the brick texture tiled 4x across the surface.",
    quiz: [{ question: "How do you make a texture tile 3 times in X and Y?", answer: "Set Scale to (3, 3, 1) in the Mapping node" }],
    practiceExercise: "Use Ctrl+T (with Node Wrangler) on an Image Texture to auto-add Texture Coordinate + Mapping. Change Scale X from 1 to 5. Watch the tiling change.",
    blenderVersion: "2.79+",
    tags: ["mapping","uv","tile","offset","rotate","scale","texture"],
  },

  {
    id: "emission",
    name: "Emission",
    category: "shader-nodes",
    subcategory: "Shader",
    icon: "💡",
    color: "yellow",
    description: "Creates a glowing, emissive surface that acts as a light source in Cycles.",
    whyItExists: "To make surfaces emit light — neon signs, screens, lava, fire, LED strips, lightsabers, any glowing object.",
    whenToUse: "When an object needs to glow or act as a light source. In Cycles it actually illuminates nearby objects. In Eevee, enable Bloom for the glow effect.",
    inputs: [
      { name: "Color", type: "Color", description: "The emission color", default: "White" },
      { name: "Strength", type: "Float", description: "Emission intensity in watts/m²", default: "1.0" },
    ],
    outputs: [{ name: "Emission", type: "Shader", description: "Emissive shader output" }],
    beginnerExplanation: "It makes your object glow like a light bulb. You pick the color and how bright it is. In Cycles, it will even light up nearby surfaces.",
    advancedExplanation: "Emission strength can go very high (100, 1000) for realistic light intensities in a physically-based scene. Use Mix Shader to combine Emission with Principled BSDF for a surface that both glows and has surface detail. In Eevee, enable Bloom in Render Properties for visible glow halos.",
    commonUseCases: ["Neon signs", "LED strips and screens", "Lava surfaces", "Lightsabers and sci-fi effects", "Self-lit objects in architectural visualization"],
    typicalConnections: ["Emission + Principled BSDF → Mix Shader → Material Output"],
    exampleWorkflow: "Neon: Emission (Color=cyan, Strength=50) → Mix Shader + Principled BSDF (as base diffuse) → Material Output. In Eevee: enable Bloom.",
    commonMistakes: ["Using Strength=1 in Cycles and wondering why it doesn't light the scene — increase to 10-100", "Not enabling Bloom in Eevee — emission visible but no halo glow"],
    performanceTips: ["High-strength Emission objects can significantly increase Cycles noise — use light portals or limit bounces"],
    relatedNodes: ["mix-shader", "principled-bsdf", "material-output"],
    frequentlyUsedWith: ["mix-shader", "principled-bsdf"],
    screenshotPlaceholder: "Emission node with cyan color and Strength=30. Connected to Material Output. The 3D viewport (rendered mode) shows the object glowing bright cyan with light spilling onto nearby objects.",
    quiz: [
      { question: "What must you enable in Eevee to see the glow halo from emission?", answer: "Bloom (in Render Properties)" },
      { question: "How do you make an object glow AND have surface detail?", answer: "Mix Emission with Principled BSDF using a Mix Shader" },
    ],
    practiceExercise: "Create a neon tube (cylinder). Add Emission shader, Color=neon pink, Strength=20. Switch to Cycles Rendered view. See how it lights nearby geometry. Try Strength 1 vs 50 vs 200.",
    blenderVersion: "2.79+",
    tags: ["emission","glow","light","neon","emissive","bloom","cycles"],
  },
];

// Build the node index for fast search
import { SHADER_NODES } from "./shader-nodes";

export const ALL_NODES = [...BLENDER_NODES, ...SHADER_NODES];

export const NODE_INDEX = ALL_NODES.map(n => ({
  id: n.id,
  name: n.name,
  category: n.category,
  subcategory: n.subcategory,
  icon: n.icon,
  color: n.color,
  tags: n.tags,
  description: n.description,
}));

export const NODE_MAP: Record<string, BlenderNode> = Object.fromEntries(
  ALL_NODES.map(n => [n.id, n])
);

export const NODES_BY_CATEGORY = BLENDER_NODES.reduce<Record<string, BlenderNode[]>>((acc, n) => {
  if (!acc[n.category]) acc[n.category] = [];
  acc[n.category].push(n);
  return acc;
}, {});
