// Blender Shader Nodes — static reference database
// Verified against Blender 4.x
import type { BlenderNode } from "./types";

export const SHADER_NODES: BlenderNode[] = [
  {
    id: "material-output",
    name: "Material Output",
    category: "shader-nodes",
    subcategory: "Output",
    icon: "◉",
    color: "green",
    blenderVersion: "2.6+",
    description: "The final node that sends the material to the render engine. Everything connects here.",
    whyItExists: "Blender needs a single endpoint to know what surface, volume, and displacement to render.",
    whenToUse: "Always. Every material must end at a Material Output node.",
    beginnerExplanation: "Think of this as the 'finish line' for your material. All your nodes flow into here to be rendered.",
    advancedExplanation: "Supports Surface (BSDFs), Volume (volume shaders), and Displacement (vector or height). Multiple Material Output nodes can exist; the one with lowest Target index is active.",
    inputs: [
      { name: "Surface", type: "Shader", description: "The surface appearance — connect a BSDF or Mix Shader here" },
      { name: "Volume", type: "Shader", description: "Volumetric material (fog, smoke, fire)" },
      { name: "Displacement", type: "Vector", description: "Surface displacement vector or height map" },
    ],
    outputs: [],
    commonUseCases: ["Final connection point for any material", "Separating surface from volume shading"],
    typicalConnections: ["Principled BSDF → Surface", "Emission → Surface", "Volume Scatter → Volume"],
    exampleWorkflow: "Principled BSDF → Material Output (Surface socket)",
    commonMistakes: ["Connecting to the wrong socket (e.g., Volume instead of Surface)", "Having multiple output nodes and being confused about which is active"],
    performanceTips: ["Unused sockets (Volume, Displacement) don't add render cost"],
    frequentlyUsedWith: ["principled-bsdf", "mix-shader", "emission"],
    relatedNodes: ["principled-bsdf", "mix-shader", "add-shader"],
    screenshotPlaceholder: "Material Output node showing Surface, Volume, and Displacement input sockets",
    quiz: [{ question: "What must every Blender material include?", answer: "A Material Output node" }],
    practiceExercise: "Create a new material and verify the Material Output node is present.",
    tags: ["output", "required", "surface", "volume"],
  },

  {
    id: "principled-bsdf",
    name: "Principled BSDF",
    category: "shader-nodes",
    subcategory: "Shader",
    icon: "◈",
    color: "blue",
    blenderVersion: "2.79+",
    description: "The all-in-one physically-based shader. Combines metallic, glass, subsurface scattering, emission, and more into one node.",
    whyItExists: "Real materials are complex combinations of properties. Principled BSDF uses the Disney PBR model so one node handles nearly everything.",
    whenToUse: "For almost all realistic surface materials — skin, metal, plastic, fabric, wood, stone.",
    beginnerExplanation: "The Swiss army knife of shaders. Start here for any real-world material. Change Base Color to set the color, Roughness to control shininess, Metallic to make it metal.",
    advancedExplanation: "Implements the Disney BSDF model. Supports multi-layer materials: base coat, specular, SSS, transmission, coat, and sheen. Anisotropy controls directional highlights. IOR controls refraction index.",
    inputs: [
      { name: "Base Color", type: "Color", description: "Primary color of the material" },
      { name: "Metallic", type: "Float", description: "0 = non-metal, 1 = full metal" },
      { name: "Roughness", type: "Float", description: "0 = perfect mirror, 1 = fully matte" },
      { name: "IOR", type: "Float", description: "Index of Refraction. Default 1.45 for glass." },
      { name: "Alpha", type: "Float", description: "Opacity. 1 = opaque, 0 = transparent." },
      { name: "Normal", type: "Vector", description: "Normal map input for surface detail" },
      { name: "Subsurface Weight", type: "Float", description: "Amount of subsurface light scattering" },
      { name: "Emission Color", type: "Color", description: "Color of light emitted by this material" },
      { name: "Emission Strength", type: "Float", description: "Brightness of emission" },
      { name: "Coat Weight", type: "Float", description: "Clear coat layer intensity (car paint, lacquer)" },
      { name: "Sheen Weight", type: "Float", description: "Velvet/fabric sheen amount" },
      { name: "Transmission Weight", type: "Float", description: "Glass-like transmission amount" },
    ],
    outputs: [
      { name: "BSDF", type: "Shader", description: "Connect to Material Output Surface" },
    ],
    commonUseCases: ["Realistic skin with SSS", "Metal surfaces", "Glass/liquid", "Plastic", "Wood", "Stone", "Fabric with sheen"],
    typicalConnections: ["Image Texture → Base Color", "Noise Texture → Roughness", "Normal Map → Normal", "BSDF → Material Output Surface"],
    exampleWorkflow: "Image Texture → Principled BSDF (Base Color) → Material Output",
    commonMistakes: [
      "Setting Metallic to 0.5 (should be 0 or 1 for real materials)",
      "Leaving Roughness at default 0.5 — everything looks the same",
      "Using Emission without high enough Strength for visibility",
    ],
    performanceTips: [
      "SSS is expensive — use Subsurface Weight only where needed",
      "Transmission requires extra render bounces — adjust in Render → Light Paths",
    ],
    frequentlyUsedWith: ["image-texture", "noise-texture", "normal-map", "color-ramp"],
    relatedNodes: ["mix-shader", "material-output", "image-texture", "noise-texture"],
    screenshotPlaceholder: "Principled BSDF node with Base Color (white), Metallic (0.0), Roughness (0.500), connected to Material Output",
    quiz: [
      { question: "What Metallic value should you use for a gold material?", answer: "1.0 (fully metallic)" },
      { question: "What controls whether a surface is mirror-like or matte?", answer: "Roughness (0 = mirror, 1 = matte)" },
    ],
    practiceExercise: "Create a gold material: set Metallic to 1.0, Roughness to 0.2, Base Color to a warm gold color.",
    tags: ["pbr", "bsdf", "realistic", "material", "surface", "principled"],
  },

  {
    id: "mix-shader",
    name: "Mix Shader",
    category: "shader-nodes",
    subcategory: "Shader",
    icon: "⟨⟩",
    color: "green",
    blenderVersion: "2.6+",
    description: "Blends two shaders together based on a factor (0–1).",
    whyItExists: "Real surfaces often combine multiple material properties. Mix Shader lets you layer and blend any two shaders.",
    whenToUse: "Whenever a material combines two shaders — wet/dry areas, worn edges, masked materials.",
    beginnerExplanation: "Opacity slider between two shaders. At 0 you get Shader 1; at 1 you get Shader 2; at 0.5 you get a 50/50 blend.",
    advancedExplanation: "Takes two BSDF inputs and a float factor. Often driven by a texture or procedural mask. Combined with Color Ramp enables sharp masked transitions.",
    inputs: [
      { name: "Fac", type: "Float", description: "0 = Shader 1, 1 = Shader 2, 0.5 = equal mix" },
      { name: "Shader", type: "Shader", description: "First shader input" },
      { name: "Shader", type: "Shader", description: "Second shader input" },
    ],
    outputs: [
      { name: "Shader", type: "Shader", description: "Blended shader output" },
    ],
    commonUseCases: ["Wet/dry surface blend", "Rust/metal edge wear", "Opacity mask for decals", "Layered materials"],
    typicalConnections: ["Fresnel → Fac", "Noise Texture → Fac via Color Ramp", "Two Principled BSDFs → Shader inputs"],
    exampleWorkflow: "Principled BSDF (dry) + Principled BSDF (wet) → Mix Shader (Fac from Noise) → Material Output",
    commonMistakes: ["Connecting to Shader socket instead of Fac for the blend factor", "Mixing incompatible shader types"],
    performanceTips: ["Driven by simple procedural textures is faster than image textures"],
    frequentlyUsedWith: ["principled-bsdf", "fresnel", "color-ramp"],
    relatedNodes: ["principled-bsdf", "add-shader", "fresnel"],
    screenshotPlaceholder: "Mix Shader node with two Shader inputs and Factor 0.500, between two Principled BSDF nodes",
    quiz: [{ question: "What value mixes two shaders equally?", answer: "Fac = 0.5" }],
    practiceExercise: "Create a material that mixes a Diffuse BSDF (red) with a Glossy BSDF (white) at 0.3 Fac.",
    tags: ["mix", "blend", "layer", "combine"],
  },

  {
    id: "add-shader",
    name: "Add Shader",
    category: "shader-nodes",
    subcategory: "Shader",
    icon: "+",
    color: "green",
    blenderVersion: "2.6+",
    description: "Adds two shaders together (additive). Both contribute fully — used for emission layering.",
    whyItExists: "Some effects require adding the energy of two shaders rather than blending — especially emission on top of a surface.",
    whenToUse: "Adding emission glow on top of a surface material. Combining translucent + diffuse for leaves.",
    beginnerExplanation: "Like placing two lights on top of each other — both shine through. Use this to add a glowing emission layer on top of a regular material.",
    advancedExplanation: "Mathematically adds radiance from both shaders. Can create unnaturally bright results if both are opaque. Best for emission + surface combinations.",
    inputs: [
      { name: "Shader", type: "Shader", description: "First shader" },
      { name: "Shader", type: "Shader", description: "Second shader (added on top)" },
    ],
    outputs: [
      { name: "Shader", type: "Shader", description: "Combined output" },
    ],
    commonUseCases: ["Glowing surface (emission + BSDF)", "Leaf/skin approximation (diffuse + translucent)"],
    typicalConnections: ["Principled BSDF + Emission → Add Shader → Material Output"],
    exampleWorkflow: "Principled BSDF + Emission → Add Shader → Material Output",
    commonMistakes: ["Using Add Shader instead of Mix Shader for material blending (causes overbright results)"],
    performanceTips: ["Can increase render complexity — use sparingly"],
    frequentlyUsedWith: ["emission", "principled-bsdf"],
    relatedNodes: ["mix-shader", "principled-bsdf", "emission"],
    screenshotPlaceholder: "Add Shader node combining a Principled BSDF and an Emission node",
    quiz: [{ question: "What's the difference between Mix Shader and Add Shader?", answer: "Mix blends between two shaders. Add combines both additively (both contribute fully)." }],
    practiceExercise: "Create a glowing rock: Principled BSDF (dark stone) + Emission (orange, strength 5) → Add Shader → Material Output.",
    tags: ["add", "emission", "layer", "additive"],
  },

  {
    id: "emission",
    name: "Emission",
    category: "shader-nodes",
    subcategory: "Shader",
    icon: "✦",
    color: "yellow",
    blenderVersion: "2.6+",
    description: "Makes a surface emit light. Used for glowing objects, screens, neon signs, fire.",
    whyItExists: "Sometimes a surface should produce light rather than react to it — emissive materials are physically accurate light sources.",
    whenToUse: "Lamps, screens, neon signs, lava, fire, glowing runes.",
    beginnerExplanation: "Makes your object glow and emit light into the scene. Connect to Material Output or Add it on top of a surface shader.",
    advancedExplanation: "Pure emission shader — no response to incoming light. Strength controls radiance in Watts/m². Works as an actual light source in path tracing.",
    inputs: [
      { name: "Color", type: "Color", description: "Color of emitted light" },
      { name: "Strength", type: "Float", description: "Emission intensity — 1.0 = standard, 10+ = bright glow" },
    ],
    outputs: [
      { name: "Emission", type: "Shader", description: "Connect to Material Output or Add Shader" },
    ],
    commonUseCases: ["Neon signs", "TV screens", "Light bulb filaments", "Lava", "Portal effects"],
    typicalConnections: ["Emission → Material Output Surface", "Emission → Add Shader"],
    exampleWorkflow: "Emission (Color: orange, Strength: 10) → Material Output Surface",
    commonMistakes: ["Strength too low — nothing visible in render", "Not enabling Bloom in Compositor for glow effect"],
    performanceTips: ["High-strength emission adds render time — use Light Objects for real scene illumination when possible"],
    frequentlyUsedWith: ["add-shader", "principled-bsdf", "material-output"],
    relatedNodes: ["add-shader", "principled-bsdf"],
    screenshotPlaceholder: "Emission node with orange Color and Strength set to 5.0",
    quiz: [{ question: "What node makes a surface emit light in Blender?", answer: "Emission node" }],
    practiceExercise: "Create a neon sign material: Emission node, Color = hot pink, Strength = 8.",
    tags: ["emission", "glow", "light", "emissive", "neon"],
  },

  {
    id: "image-texture",
    name: "Image Texture",
    category: "shader-nodes",
    subcategory: "Texture",
    icon: "🖼",
    color: "yellow",
    blenderVersion: "2.6+",
    description: "Loads an external image file and uses it as a texture. The most common way to apply photographs and PBR maps.",
    whyItExists: "Real-world texture detail (wood grain, fabric, skin pores) is captured in photographs that need to be applied to 3D surfaces.",
    whenToUse: "Applying photo textures, PBR texture maps (Albedo, Normal, Roughness, AO), custom painted textures, decals.",
    beginnerExplanation: "Like pasting a photograph onto your 3D object. Open an image file, and it wraps around the surface using UV coordinates.",
    advancedExplanation: "Supports multiple Color Space modes (sRGB for color, Non-Color for data maps). Extension controls tiling behavior. Interpolation affects sampling quality.",
    inputs: [
      { name: "Vector", type: "Vector", description: "UV coordinates — connect Texture Coordinate → UV" },
    ],
    outputs: [
      { name: "Color", type: "Color", description: "RGB color output from the image" },
      { name: "Alpha", type: "Float", description: "Alpha channel from the image" },
    ],
    commonUseCases: ["PBR albedo maps", "Normal maps (Color Space: Non-Color)", "Roughness maps", "Photo-realistic texturing"],
    typicalConnections: ["Texture Coordinate (UV) → Vector", "Color → Principled BSDF Base Color", "Color → Normal Map → Normal"],
    exampleWorkflow: "Texture Coordinate → Image Texture → Principled BSDF Base Color",
    commonMistakes: [
      "Using sRGB color space for normal maps (causes distorted lighting)",
      "Not connecting UV coordinates — results in incorrect tiling",
      "Forgetting to pack the image into the .blend file",
    ],
    performanceTips: ["Use 2K textures for most objects, 4K only for hero assets visible up close"],
    frequentlyUsedWith: ["texture-coordinate", "mapping", "normal-map", "principled-bsdf"],
    relatedNodes: ["texture-coordinate", "mapping", "principled-bsdf", "normal-map"],
    screenshotPlaceholder: "Image Texture node with an image loaded, Color Space set to sRGB, showing Color and Alpha outputs",
    quiz: [
      { question: "What Color Space should you use for a normal map?", answer: "Non-Color" },
      { question: "What input controls UV mapping on Image Texture?", answer: "The Vector input — connect Texture Coordinate → UV" },
    ],
    practiceExercise: "Load a wood grain texture. Set Color Space to sRGB. Connect: Texture Coordinate → Mapping → Image Texture → Principled BSDF Base Color.",
    tags: ["texture", "image", "photo", "uv", "pbr", "albedo"],
  },

  {
    id: "noise-texture",
    name: "Noise Texture",
    category: "shader-nodes",
    subcategory: "Texture",
    icon: "~",
    color: "purple",
    blenderVersion: "2.6+",
    description: "Generates procedural Perlin noise — the foundation of most procedural textures.",
    whyItExists: "Natural surfaces (rock, clouds, water turbulence) have random variation that procedural noise can simulate without any image files.",
    whenToUse: "Procedural displacement, cloud/fog patterns, surface imperfections, bump details, random variation.",
    beginnerExplanation: "Creates a random cloudy black-and-white pattern. Plug it into almost anything to add organic variation — roughness, color, bump.",
    advancedExplanation: "Uses Perlin noise algorithm. Scale controls frequency, Detail adds octaves, Roughness controls high-frequency dominance, Distortion warps noise internally. W adds 4D variation for animation.",
    inputs: [
      { name: "Vector", type: "Vector", description: "3D coordinate input" },
      { name: "W", type: "Float", description: "4D noise coordinate — animate for evolving noise" },
      { name: "Scale", type: "Float", description: "Controls noise frequency. Higher = smaller pattern." },
      { name: "Detail", type: "Float", description: "Octaves of noise layered together. Higher = more detail." },
      { name: "Roughness", type: "Float", description: "How much detail octaves contribute. 0 = smooth, 1 = rough." },
      { name: "Distortion", type: "Float", description: "Internally warps the noise coordinates for organic swirling." },
    ],
    outputs: [
      { name: "Fac", type: "Float", description: "Grayscale noise value (0–1)" },
      { name: "Color", type: "Color", description: "RGB version of the noise" },
    ],
    commonUseCases: ["Rock/stone surface detail", "Cloud patterns", "Water surface displacement", "Roughness variation", "Procedural dirt/wear"],
    typicalConnections: ["Fac → Color Ramp → Roughness", "Fac → Bump → Normal", "Fac → Displacement → Material Output"],
    exampleWorkflow: "Noise Texture (Scale: 5, Detail: 8) → Color Ramp → Principled BSDF Roughness",
    commonMistakes: ["Forgetting to change Scale from default", "Using Color output instead of Fac for grayscale connections"],
    performanceTips: ["Keep Detail below 12 — diminishing returns above that, but render time keeps increasing"],
    frequentlyUsedWith: ["color-ramp", "bump", "mapping"],
    relatedNodes: ["voronoi-texture", "color-ramp", "mapping"],
    screenshotPlaceholder: "Noise Texture node with Scale at 5.0, Detail at 8.0, showing a cloudy greyscale preview",
    quiz: [{ question: "What Noise Texture parameter controls the pattern size?", answer: "Scale — higher values create smaller patterns" }],
    practiceExercise: "Add Noise Texture (Scale 8, Detail 6). Connect Fac → Color Ramp → Principled BSDF Roughness.",
    tags: ["noise", "procedural", "perlin", "organic", "random"],
  },

  {
    id: "voronoi-texture",
    name: "Voronoi Texture",
    category: "shader-nodes",
    subcategory: "Texture",
    icon: "◆",
    color: "orange",
    blenderVersion: "2.6+",
    description: "Generates cell-based patterns — cracked earth, scales, cobblestones, cell structures.",
    whyItExists: "Many natural patterns are Voronoi-based — biological cells, cracked mud, scales, cobblestones.",
    whenToUse: "Cracked earth, reptile scales, cobblestone streets, cell structures, alien skin.",
    beginnerExplanation: "Makes patterns that look like cracked mud or honeycomb cells. Great for scales and cell structures.",
    advancedExplanation: "Based on Voronoi diagram — measures distance from each point to the nearest seed point. Feature controls output type. Smoothness blurs between cells for organic shapes.",
    inputs: [
      { name: "Vector", type: "Vector", description: "Coordinate input" },
      { name: "Scale", type: "Float", description: "Cell density — higher = smaller cells" },
      { name: "Detail", type: "Float", description: "Added detail octaves" },
      { name: "Roughness", type: "Float", description: "Detail roughness" },
      { name: "Randomness", type: "Float", description: "0 = uniform grid, 1 = fully random cell placement" },
    ],
    outputs: [
      { name: "Distance", type: "Float", description: "Distance to nearest cell center" },
      { name: "Color", type: "Color", description: "Random color per cell" },
      { name: "Position", type: "Vector", description: "Position of nearest cell center" },
    ],
    commonUseCases: ["Cracked mud/earth", "Reptile scales", "Cobblestone", "Cell shading"],
    typicalConnections: ["Distance → Color Ramp → Displacement", "Distance → Bump → Normal"],
    exampleWorkflow: "Voronoi Texture → Color Ramp → Displacement → Material Output",
    commonMistakes: ["Using Color output for bump maps instead of Distance", "Scale too low — cells too large"],
    performanceTips: ["More expensive than Noise — use only where cells are needed"],
    frequentlyUsedWith: ["color-ramp", "noise-texture"],
    relatedNodes: ["noise-texture", "color-ramp", "wave-texture"],
    screenshotPlaceholder: "Voronoi Texture showing a cell pattern with Scale 5.0 and Randomness 1.0",
    quiz: [{ question: "Which Voronoi output creates a grayscale distance map for bumps?", answer: "Distance" }],
    practiceExercise: "Create cracked earth: Voronoi (Scale 8, Feature = Distance to Edge) → Color Ramp → Displacement.",
    tags: ["voronoi", "cells", "procedural", "cracks", "scales"],
  },

  {
    id: "wave-texture",
    name: "Wave Texture",
    category: "shader-nodes",
    subcategory: "Texture",
    icon: "≈",
    color: "blue",
    blenderVersion: "2.6+",
    description: "Generates regular wave patterns — rings, bands, stripes. Great for wood grain and water ripples.",
    whyItExists: "Regular repeating patterns (wood grain, water ripples, fabric stripes) need a wave function rather than noise.",
    whenToUse: "Wood grain, water rings, striped fabric, concentric ring patterns.",
    beginnerExplanation: "Makes stripes or rings. Use Bands for wood grain. Use Rings for concentric circles like a log cross-section.",
    advancedExplanation: "Generates sinusoidal wave patterns. Distortion adds Noise-based turbulence. Phase Offset animates wave position. Detail adds high-frequency wave complexity.",
    inputs: [
      { name: "Vector", type: "Vector", description: "Coordinate input" },
      { name: "Scale", type: "Float", description: "Wave frequency — higher = more waves" },
      { name: "Distortion", type: "Float", description: "Adds noise-based distortion to the wave pattern" },
      { name: "Detail", type: "Float", description: "High-frequency wave detail" },
      { name: "Detail Scale", type: "Float", description: "Scale of detail pattern" },
      { name: "Phase Offset", type: "Float", description: "Shifts wave phase — animate for moving water" },
    ],
    outputs: [
      { name: "Color", type: "Color", description: "Wave pattern as color" },
      { name: "Fac", type: "Float", description: "Wave pattern as float" },
    ],
    commonUseCases: ["Wood grain (Bands, high Distortion)", "Water ripples (Rings, animate Phase Offset)", "Striped fabric"],
    typicalConnections: ["Fac → Color Ramp → Base Color", "Fac → Bump → Normal"],
    exampleWorkflow: "Wave Texture (Bands, Scale: 10, Distortion: 2) → Color Ramp → Principled BSDF Base Color",
    commonMistakes: ["Forgetting Distortion (plain waves look artificial)", "Using Rings instead of Bands for wood grain"],
    performanceTips: ["Wave is very cheap — use freely"],
    frequentlyUsedWith: ["color-ramp", "mapping", "noise-texture"],
    relatedNodes: ["noise-texture", "color-ramp", "mapping"],
    screenshotPlaceholder: "Wave Texture set to Bands type with Scale 10 and Distortion 2, showing wavy stripe pattern in preview",
    quiz: [{ question: "Which Wave type creates concentric ring patterns like a log cross-section?", answer: "Rings" }],
    practiceExercise: "Create wood grain: Wave Texture (Bands, Scale 15, Distortion 3) → Color Ramp (brown tones) → Principled BSDF Base Color.",
    tags: ["wave", "bands", "rings", "wood", "procedural", "stripes"],
  },

  {
    id: "color-ramp",
    name: "Color Ramp",
    category: "shader-nodes",
    subcategory: "Color",
    icon: "▬",
    color: "orange",
    blenderVersion: "2.6+",
    description: "Maps a float value (0–1) to a gradient of colors. The most versatile node for controlling texture appearance.",
    whyItExists: "Raw texture outputs (like Noise Fac) are continuous gradients that often need remapping to specific color ranges or contrast.",
    whenToUse: "Virtually everywhere — adjusting contrast, creating color gradients from grayscale, masking, posterizing.",
    beginnerExplanation: "Takes a black-to-white gradient and lets you remap it to any colors you want. Drag the stops to create sharp masks or smooth blends. One of the most useful nodes.",
    advancedExplanation: "Full gradient editor with multiple color stops, interpolation modes (Linear, Ease, B-Spline, Cardinal, Constant). Constant mode creates hard edges for stylized effects.",
    inputs: [
      { name: "Fac", type: "Float", description: "Input value 0–1 — maps to position on the gradient" },
    ],
    outputs: [
      { name: "Color", type: "Color", description: "Color from the gradient at the given Fac position" },
      { name: "Alpha", type: "Float", description: "Alpha value at the given Fac position" },
    ],
    commonUseCases: ["Noise → Color Ramp for terrain colors", "Fresnel → Color Ramp for rim light control", "Sharpen soft procedural masks"],
    typicalConnections: ["Noise Fac → Fac", "Voronoi Distance → Fac", "Color → Principled BSDF Base Color or Roughness"],
    exampleWorkflow: "Noise Texture (Fac) → Color Ramp → Principled BSDF Roughness",
    commonMistakes: ["Connecting Color output to a socket expecting Float", "Too many stops creating a messy gradient"],
    performanceTips: ["Essentially free — one of the cheapest nodes available"],
    frequentlyUsedWith: ["noise-texture", "voronoi-texture", "principled-bsdf"],
    relatedNodes: ["noise-texture", "voronoi-texture", "mix-rgb"],
    screenshotPlaceholder: "Color Ramp node in Linear mode with a white-to-black gradient, two stops visible",
    quiz: [{ question: "What Interpolation mode creates hard transitions between colors in Color Ramp?", answer: "Constant" }],
    practiceExercise: "Connect Noise Texture (Fac) to Color Ramp. Add a brown stop at 0.3 and lighter brown at 0.7. Connect Color → Principled BSDF Base Color.",
    tags: ["ramp", "gradient", "color", "mask", "remap", "contrast"],
  },

  {
    id: "mix-rgb",
    name: "Mix Color",
    category: "shader-nodes",
    subcategory: "Color",
    icon: "⊕",
    color: "orange",
    blenderVersion: "2.6+",
    description: "Blends two colors together using various blend modes (Multiply, Screen, Overlay, etc.).",
    whyItExists: "Photoshop-style color blending operations are needed in shader networks to layer textures and adjust tones.",
    whenToUse: "Multiplying AO maps onto color, overlaying procedural grunge, blending two textures.",
    beginnerExplanation: "Like Photoshop blend modes for nodes. Multiply darkens where one texture is dark. Screen brightens. Overlay boosts contrast.",
    advancedExplanation: "Supports all standard blend modes. The Clamp toggle prevents values exceeding 0–1. Factor controls blend strength.",
    inputs: [
      { name: "Factor", type: "Float", description: "0 = use Color A only, 1 = full blend mode applied" },
      { name: "A", type: "Color", description: "Base color" },
      { name: "B", type: "Color", description: "Blend color" },
    ],
    outputs: [
      { name: "Result", type: "Color", description: "Blended color output" },
    ],
    commonUseCases: ["Multiply AO into diffuse texture", "Overlay grunge map", "Tint with color"],
    typicalConnections: ["Image Texture (Albedo) → A", "AO Texture → B", "Result → Principled BSDF Base Color"],
    exampleWorkflow: "Image Texture (Albedo) + AO Texture → Mix Color (Multiply) → Principled BSDF Base Color",
    commonMistakes: ["Using wrong blend mode — Multiply darkens, Screen brightens"],
    performanceTips: ["Essentially free"],
    frequentlyUsedWith: ["image-texture", "color-ramp", "principled-bsdf"],
    relatedNodes: ["color-ramp", "image-texture"],
    screenshotPlaceholder: "Mix Color node in Multiply mode with Factor at 1.0, two color inputs connected",
    quiz: [{ question: "Which Mix Color blend mode darkens the result?", answer: "Multiply" }],
    practiceExercise: "Mix two colors using Overlay mode at 0.5 Factor.",
    tags: ["mix", "blend", "color", "multiply", "overlay", "screen"],
  },

  {
    id: "texture-coordinate",
    name: "Texture Coordinate",
    category: "shader-nodes",
    subcategory: "Input",
    icon: "⊞",
    color: "purple",
    blenderVersion: "2.6+",
    description: "Provides UV, Object, Camera, World, Normal, and Window coordinate systems for texture mapping.",
    whyItExists: "Textures need to know WHERE on the object to sample. Different coordinate types control how a texture wraps around geometry.",
    whenToUse: "Always when controlling texture mapping — pair with Mapping node for offset/scale/rotation control.",
    beginnerExplanation: "Controls how the texture wraps around the object. UV is the standard way. Object coordinates are useful for procedural textures that don't need UV unwrapping.",
    advancedExplanation: "UV requires proper UV unwrapping. Generated uses normalized bounding box coordinates. Object uses local object space. Window is screen-space projection.",
    inputs: [],
    outputs: [
      { name: "Generated", type: "Vector", description: "Bounding box normalized coordinates (0–1)" },
      { name: "Normal", type: "Vector", description: "Surface normal direction" },
      { name: "UV", type: "Vector", description: "UV map coordinates — requires UV unwrap" },
      { name: "Object", type: "Vector", description: "Object-space coordinates" },
      { name: "Camera", type: "Vector", description: "Camera-relative coordinates" },
      { name: "Window", type: "Vector", description: "Screen-space (2D) coordinates" },
      { name: "Reflection", type: "Vector", description: "Reflection direction — for environment maps" },
    ],
    commonUseCases: ["Feeding UV coordinates to Image Texture", "Object coordinates for seamless procedural textures", "Reflection for environment mapping"],
    typicalConnections: ["UV → Mapping → Image Texture Vector", "Object → Noise Texture Vector"],
    exampleWorkflow: "Texture Coordinate (UV) → Mapping → Image Texture",
    commonMistakes: ["Using UV without actually UV-unwrapping the mesh", "Forgetting to add a Mapping node between Texture Coordinate and Image Texture"],
    performanceTips: ["No computation cost — just coordinate lookup"],
    frequentlyUsedWith: ["mapping", "image-texture", "noise-texture"],
    relatedNodes: ["mapping", "image-texture"],
    screenshotPlaceholder: "Texture Coordinate node showing all output sockets: Generated, Normal, UV, Object, Camera, Window, Reflection",
    quiz: [{ question: "Which Texture Coordinate output requires UV unwrapping?", answer: "UV" }],
    practiceExercise: "Add Texture Coordinate → Mapping → Image Texture chain. Try switching between UV and Object outputs.",
    tags: ["uv", "coordinates", "mapping", "object-space", "generated"],
  },

  {
    id: "mapping",
    name: "Mapping",
    category: "shader-nodes",
    subcategory: "Vector",
    icon: "⊿",
    color: "purple",
    blenderVersion: "2.6+",
    description: "Controls how a texture maps onto a surface — offset position, rotation, and scale.",
    whyItExists: "Texture Coordinate gives raw coordinates. Mapping transforms them — move the texture, rotate it, tile it.",
    whenToUse: "Whenever you need to adjust texture position, scale (tiling), or rotation.",
    beginnerExplanation: "The dial that controls how the texture sits on the surface. Location moves it. Rotation spins it. Scale tiles it more or tighter.",
    advancedExplanation: "Equivalent to a transformation matrix applied to UV/texture space. Scale values above 1 tile more (smaller pattern). Rotation in radians.",
    inputs: [
      { name: "Vector", type: "Vector", description: "Input coordinates (from Texture Coordinate)" },
      { name: "Location", type: "Vector", description: "Offset X/Y/Z" },
      { name: "Rotation", type: "Vector", description: "Rotation in radians" },
      { name: "Scale", type: "Vector", description: "Scale X/Y/Z — higher = more tiles" },
    ],
    outputs: [
      { name: "Vector", type: "Vector", description: "Transformed coordinates — connect to Image Texture Vector" },
    ],
    commonUseCases: ["Tiling a texture to the correct scale", "Rotating a wood grain texture", "Offsetting a pattern for variation"],
    typicalConnections: ["Texture Coordinate → Vector", "Vector → Image Texture Vector"],
    exampleWorkflow: "Texture Coordinate (UV) → Mapping (Scale 4,4,4) → Image Texture",
    commonMistakes: ["Scale of 0 makes texture disappear", "Expecting Location to work in world units (it's UV space)"],
    performanceTips: ["Free node — no render cost"],
    frequentlyUsedWith: ["texture-coordinate", "image-texture", "noise-texture"],
    relatedNodes: ["texture-coordinate", "image-texture"],
    screenshotPlaceholder: "Mapping node with Location (0,0,0), Rotation (0,0,0), Scale (4,4,4) inputs visible",
    quiz: [{ question: "What Mapping Scale value would tile a texture twice as many times?", answer: "2 (e.g. Scale X: 2, Y: 2)" }],
    practiceExercise: "Add Mapping node with Scale X: 4, Y: 4 between Texture Coordinate and Image Texture to tile the texture 4x.",
    tags: ["mapping", "tiling", "rotation", "offset", "uv-transform"],
  },

  {
    id: "normal-map",
    name: "Normal Map",
    category: "shader-nodes",
    subcategory: "Vector",
    icon: "⟂",
    color: "purple",
    blenderVersion: "2.6+",
    description: "Converts a normal map image (blue-purple) into actual surface normal vectors for fake surface detail.",
    whyItExists: "Detailed geometry is expensive. Normal maps fake micro-surface detail using an image at almost no cost.",
    whenToUse: "Whenever you have a normal map texture from a PBR texture set. Nearly every realistic material uses one.",
    beginnerExplanation: "Takes the blue-purple normal map image and tells Blender where the tiny bumps and dents are. Connect Image Texture (Non-Color) → Normal Map → Principled BSDF Normal.",
    advancedExplanation: "Transforms tangent-space normal maps (RGB encoded) into object-space vectors. Strength controls how pronounced the effect is. Supports Tangent, Object, World, and Blender Object spaces.",
    inputs: [
      { name: "Strength", type: "Float", description: "Normal map intensity. 1.0 = standard." },
      { name: "Color", type: "Color", description: "The normal map image (set Image Texture Color Space to Non-Color)" },
    ],
    outputs: [
      { name: "Normal", type: "Vector", description: "Connect to Principled BSDF Normal input" },
    ],
    commonUseCases: ["PBR texture set normal maps", "Sculpt baked normal maps", "Adding surface detail without geometry"],
    typicalConnections: ["Image Texture (Non-Color) → Color", "Normal → Principled BSDF Normal"],
    exampleWorkflow: "Image Texture (normal.png, Non-Color) → Normal Map → Principled BSDF Normal",
    commonMistakes: [
      "Not setting Image Texture Color Space to Non-Color",
      "Strength too high — looks like shattered glass",
      "Not chaining Bump and Normal Map when using both",
    ],
    performanceTips: ["Normal maps add virtually no render time compared to actual geometry"],
    frequentlyUsedWith: ["image-texture", "bump", "principled-bsdf"],
    relatedNodes: ["image-texture", "bump", "principled-bsdf"],
    screenshotPlaceholder: "Normal Map node with Strength 1.0, connected from Image Texture (blue-purple image) to Principled BSDF Normal",
    quiz: [{ question: "What Color Space should a normal map Image Texture be set to?", answer: "Non-Color" }],
    practiceExercise: "Import a normal map. Add Image Texture (Color Space: Non-Color) → Normal Map (Strength: 1.0) → Principled BSDF Normal.",
    tags: ["normal", "bump", "detail", "pbr", "tangent"],
  },

  {
    id: "bump",
    name: "Bump",
    category: "shader-nodes",
    subcategory: "Vector",
    icon: "∧",
    color: "purple",
    blenderVersion: "2.6+",
    description: "Converts a grayscale height map into surface normals for bump mapping.",
    whyItExists: "Grayscale height textures (Noise, hand-painted) need conversion to normals for lighting calculations.",
    whenToUse: "When you have a grayscale height map (not a proper normal map). Also to add procedural bump on top of a normal map.",
    beginnerExplanation: "Like Normal Map but takes a black-and-white height image instead of the blue-purple normal map. White = raised, Black = depressed.",
    advancedExplanation: "Computes surface normal from grayscale height gradient. Distance scales bump in object space. Can be chained with Normal Map by connecting Normal Map output to Bump Normal input.",
    inputs: [
      { name: "Strength", type: "Float", description: "Bump intensity — 1.0 standard, higher = more pronounced" },
      { name: "Distance", type: "Float", description: "Physical distance of the bump in object space" },
      { name: "Height", type: "Float", description: "Grayscale height map input" },
      { name: "Normal", type: "Vector", description: "Optional: chain with Normal Map" },
    ],
    outputs: [
      { name: "Normal", type: "Vector", description: "Connect to Principled BSDF Normal" },
    ],
    commonUseCases: ["Adding procedural bumps from Noise Texture", "Combining height map on top of normal map", "Quick bump without UV unwrapping"],
    typicalConnections: ["Noise Texture Fac → Height", "Normal → Principled BSDF Normal", "Normal Map Normal → Normal (to chain)"],
    exampleWorkflow: "Noise Texture (Fac) → Bump → Principled BSDF Normal",
    commonMistakes: ["Strength too high — looks broken/black", "Not chaining Bump and Normal Map (chain them via Normal input)"],
    performanceTips: ["Cheaper than Normal Map for procedural textures"],
    frequentlyUsedWith: ["noise-texture", "normal-map", "principled-bsdf"],
    relatedNodes: ["normal-map", "noise-texture", "principled-bsdf"],
    screenshotPlaceholder: "Bump node with Strength 0.5, Distance 0.1, connected from Noise Texture to Principled BSDF Normal",
    quiz: [{ question: "What color represents a raised surface in a Bump node height map?", answer: "White (bright values = raised)" }],
    practiceExercise: "Add Noise Texture (Fac) → Bump (Strength: 0.3) → Principled BSDF Normal for procedural surface bumps.",
    tags: ["bump", "height", "detail", "normal", "procedural"],
  },

  {
    id: "fresnel",
    name: "Fresnel",
    category: "shader-nodes",
    subcategory: "Input",
    icon: "◡",
    color: "blue",
    blenderVersion: "2.6+",
    description: "Outputs how much a surface reflects based on viewing angle — brighter at grazing angles, darker head-on.",
    whyItExists: "Real surfaces reflect more at grazing angles (the Fresnel effect). This node gives you control over that reflection gradient.",
    whenToUse: "Rim light effects, car paint, wet surface edge reflection, adding sheen to fabric edges.",
    beginnerExplanation: "Makes the edges of objects brighter — think of a glass ball where the edges are more reflective than the center.",
    advancedExplanation: "Outputs the Fresnel factor using the Schlick approximation. IOR controls the steepness — higher IOR = reflective even at non-grazing angles.",
    inputs: [
      { name: "IOR", type: "Float", description: "Index of Refraction — 1.45 for glass, 1.0 for flat response" },
      { name: "Normal", type: "Vector", description: "Custom normal — leave unconnected for surface normal" },
    ],
    outputs: [
      { name: "Fac", type: "Float", description: "Fresnel factor — 0 at center, 1 at edges" },
    ],
    commonUseCases: ["Edge rim lighting", "Mix Shader factor for edge gloss", "Car paint metallic flakes at angles"],
    typicalConnections: ["Fac → Mix Shader Fac", "Fac → Color Ramp → Mix Shader Fac"],
    exampleWorkflow: "Fresnel (IOR: 1.45) → Mix Shader Fac → blend Diffuse + Glossy",
    commonMistakes: ["IOR too high makes the whole surface reflective"],
    performanceTips: ["Essentially free"],
    frequentlyUsedWith: ["mix-shader", "color-ramp", "principled-bsdf"],
    relatedNodes: ["mix-shader", "principled-bsdf"],
    screenshotPlaceholder: "Fresnel node with IOR at 1.450, output Fac connected to Mix Shader",
    quiz: [{ question: "What real physical phenomenon does the Fresnel node simulate?", answer: "More reflection at grazing angles — the Fresnel effect" }],
    practiceExercise: "Add Fresnel (IOR: 1.45) → Color Ramp → Mix Shader to blend a Diffuse and Glossy shader based on view angle.",
    tags: ["fresnel", "reflection", "angle", "rim", "ior"],
  },
];

export const SHADER_NODE_INDEX = SHADER_NODES.map(n => ({
  id: n.id,
  name: n.name,
  category: n.category,
  subcategory: n.subcategory,
  icon: n.icon,
  color: n.color,
  description: n.description,
  tags: n.tags,
}));

export const SHADER_NODE_MAP = Object.fromEntries(SHADER_NODES.map(n => [n.id, n]));
